### ISSUE TITLE
Building on Raspbian - Raspberry PI 3 - Errors and workaround

### ISSUE THREAD

**Issue by Injac** [Azure/azure-iot-gateway-sdk#1]
Trying to build the gateway sources on a PI 3, using the **build.sh** script, fails with the following error:

`[ 43%] Building C object deps/azure-iot-sdks/c/azure-uamqp-c/tests/session_unittests/CMakeFiles/session_unittests_exe.dir/main.c.o
Linking CXX executable session_unittests_exe
Linking CXX executable mqtt_client_unittests_exe
[ 43%] Built target session_unittests_exe
[ 43%] Built target mqtt_client_unittests_exe
The bug is not reproducible, so it is likely a hardware or OS problem.
deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_unittests/CMakeFiles/saslclientio_unittests_exe.dir/build.make:54: recipe for target 'deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_unittests/CMakeFiles/saslclientio_unittests_exe.dir/saslclientio_unittests.cpp.o' failed
make[2]: *** [deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_unittests/CMakeFiles/saslclientio_unittests_exe.dir/saslclientio_unittests.cpp.o] Error 1
CMakeFiles/Makefile2:4415: recipe for target 'deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_unittests/CMakeFiles/saslclientio_unittests_exe.dir/all' failed
make[1]: *** [deps/azure-iot-sdks/c/azure-uamqp-c/tests/saslclientio_unittests/CMakeFiles/saslclientio_unittests_exe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

A manual build using **make -j $(nproc)** fails as well. Whereas omitting the **-j $(nproc)** parameter for make in general, compiles successfully.

Afterwards, test can be run manually using **ctest -j $(nproc) -C Debug --output-on-failure** most of the tests will run successfully, except for the **unmocktypes_c_unittests**:

`99% tests passed, 1 tests failed out of 97

Total Test time (real) =   4.13 sec

The following tests FAILED:
	 12 - umocktypes_c_unittests (Failed)
Errors while running CTest`

I am going to test the gateway code further. Trying examples, etc.. If you need additional files like logs, let me know.

**Comment by andrew-buckley** [comment]
Hi @Injac, which operating system are you using on your Pi 3?

**Comment by Injac** [comment]
Hi @andrew-buckley ,

I am using Raspian 4.1. Here are the kernel informations (and some more):

**Linux gate369 4.1.20-v7+ #867 SMP Wed Mar 23 20:12:32 GMT 2016 armv7l GNU/Linux**

cat /proc/version output:

**Linux version 4.1.20-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #867 SMP Wed Mar 23 20:12:32 GMT 2016**

output lsb_release -da 

**Distributor ID:	Raspbian**
**Description:	Raspbian GNU/Linux 8.0 (jessie)**
**Release:	8.0**
**Codename:	jessie**

**Comment by Injac** [comment]
Sorry, hit the wrong button. Accidentally closed the issue.

**Comment by avranju** [comment]
Thanks for the report @Injac. I was able to reproduce the test case failure (`umocktypes_c_unittests`) on a Raspberry Pi 3. We're getting this addressed.

**Comment by Injac** [comment]
Ok. Thanks for taking care of this @avranju .

**Comment by dcristoloveanu** [comment]
@Injac A fix for this has been checked in to the develop branch.
Thanks for reporting it!
/Dan

**Comment by Injac** [comment]
@dcristoloveanu Thanks for the quick fix :)
