### ISSUE TITLE
how to best ship a gateway sample/product

### ISSUE THREAD

**Issue by asac** [Azure/azure-iot-gateway-sdk#107]
Hi,

it is easy enough to use the azure-iot-gateway-sdk to develop and hack on a gateway. Building the samples is easy and running the ble_gateway also works with some effort, but I couldn't figure how to really package things up so that I have everything that is needed to run ble_gateway nicely together in one folder...

maybe running make install DESTDIR=/target/folder/to/zip/up in the samples/ble_gateway directory could just make a nice tree with everyhing including modules under DESTDIR that one could just zip up and then deploy in products?

Thanks!

**Comment by asac** [comment]
alternatively what would be super great would be to have a way to link everything statically into one binary. This would making shipping the product of the sdk work super easy and portable.

**Comment by darobs** [comment]
Hello @asac, working on a packaging story for all the platforms we support is on the roadmap. 

In the meantime, I'm building the repo to see what exactly we need to make a proper package on both Windows and Linux.  It's been a while since I've tried this, so I want to make sure I have it right.

**Comment by darobs** [comment]
On Linux, the core gateway needs:
```
    libaziotsharedutil.so
    libgateway.so
    libnanomsg.so
```
That's enough to start the gateway, but to run one or more samples, you will also need the modules:
```
    libble.so  
    libhello_world.so  
    libidentity_map.so  
    libiothub.so 
    liblogger.so  
    libsimulated_device.so
```
plus
```
    libiothub_client.so (currently required by libiothub.so)
```

If you want high level binding, we'll need these binding libraries:
```
    libjava_module_host.so
    libnodejs_binding.so
```
plus
```
    node.dll (required by libnodejs_binding.so)
```

We did consider putting everything into one big static library, but we want the modules to be loaded and unloaded dynamically. This means the modules are built as shared libraries. We also want the modules to use the same version of the gateway, nanomsg and aziotsharedutil libraries as the gateway core.  Making them shared libraries guarantees the modules and gateway both will use the same library loaded in memory.

BTW, Windows is similar, with the additional dotnet binding library.

Note that we can install this all in one directory.  I used this cmake command in Linux to build and install our libraries in a custom location ($HOME/repos/bins):
```
cmake -DCMAKE_INSTALL_PREFIX:STRING=$HOME/repos/bins -DCMAKE_BUILD_TYPE=Debug -Ddependency_install_prefix=$HOME/repos/bins -Dinstall_modules=ON -Denable_nodejs_binding=ON Denable_java_binding=ON  ..
cmake --build . --target install --
```

I hope this helps!
Dave Robson

**Comment by damonbarry** [comment]
I'll also add that we've tried to leave open the possibility of building everything statically, although I hasn't been extensively tested. One missing piece we know about is a static loader so the gateway can call statically-linked modules; this is not a difficult piece to write, it just hasn't been a high enough priority. Running the gateway on an embedded OS would require this.

**Comment by asac** [comment]
thanks for the guidance. This worked, but it still does not install the sample it self (though it builds it)
