### ISSUE TITLE
azure-iot-field-gateway-sdk.bb bitbake failed

### ISSUE THREAD

**Issue by gerrik84** [Azure/azure-iot-gateway-sdk#109]
Hi,
since i updated the repository i'm not able to build the azure-iot-field-gateway-sdk.bb recipe. 

My build System: 
```
Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "i586-poky-linux"
MACHINE           = "edison"
DISTRO            = "poky-edison"
DISTRO_VERSION    = "1.7.3"
TUNE_FEATURES     = "m32 core2"
TARGET_FPU        = ""
```

Also tested with:
```
Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "i586-poky-linux"
MACHINE           = "edison"
DISTRO            = "poky-edison"
DISTRO_VERSION    = "1.7.2"
TUNE_FEATURES     = "m32 core2"
TARGET_FPU        = ""
```

Error log:

> ERROR: Function failed: do_configure (log file is located at /home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/temp/log.do_configure.19884)
> ERROR: Logfile of failure stored in: /home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/temp/log.do_configure.19884
> Log data follows:
> | DEBUG: Executing python function sysroot_cleansstate
> | DEBUG: Python function sysroot_cleansstate finished
> | DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
> | DEBUG: Executing shell function autotools_preconfigure
> | DEBUG: Shell function autotools_preconfigure finished
> | DEBUG: Executing python function autotools_copy_aclocals
> | DEBUG: Python function autotools_copy_aclocals finished
> | DEBUG: Executing shell function do_configure
> | -- The C compiler identification is GNU 4.9.1
> | -- The CXX compiler identification is GNU 4.9.1
> | -- Check for working C compiler: /home/intrsol/edison-src-16/build_edison/tmp/sysroots/x86_64-linux/usr/bin/i586-poky-linux/i586-poky-linux-gcc
> | -- Check for working C compiler: /home/intrsol/edison-src-16/build_edison/tmp/sysroots/x86_64-linux/usr/bin/i586-poky-linux/i586-poky-linux-gcc -- works
> | -- Detecting C compiler ABI info
> | -- Detecting C compiler ABI info - done
> | -- Detecting C compile features
> | -- Detecting C compile features - done
> | -- Check for working CXX compiler: /home/intrsol/edison-src-16/build_edison/tmp/sysroots/x86_64-linux/usr/bin/i586-poky-linux/i586-poky-linux-g++
> | -- Check for working CXX compiler: /home/intrsol/edison-src-16/build_edison/tmp/sysroots/x86_64-linux/usr/bin/i586-poky-linux/i586-poky-linux-g++ -- works
> | -- Detecting CXX compiler ABI info
> | -- Detecting CXX compiler ABI info - done
> | -- Detecting CXX compile features
> | -- Detecting CXX compile features - done
> | -- CMake Install Prefix is /usr
> | -- AIG architecture: x86
> | -- ctest not found...
> | -- Building ctest...
> | -- Configuring done
> | -- Generating done
> | -- Build files have been written to: /home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/home/azure-iot-gateway-sdk/deps/ctest/build
> | -- Installing ctest. Please wait...
> | CMake Error at gatewayFunctions.cmake:123 (message):
> |   Error installing ctest: 2
> | Call Stack (most recent call first):
> |   dependencies-test.cmake:9 (findAndInstall)
> |   CMakeLists.txt:163 (include)
> | 
> | 
> | -- Configuring incomplete, errors occurred!
> | See also "/home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/build/CMakeFiles/CMakeOutput.log".
> | See also "/home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/build/CMakeFiles/CMakeError.log".
> | WARNING: exit code 1 from a shell command.
> | ERROR: Function failed: do_configure (log file is located at /home/intrsol/edison-src-16/build_edison/tmp/work/core2-32-poky-linux/azure-iot-field-gateway-sdk/1.0-r0/temp/log.do_configure.19884)
> ERROR: Task 1615 (/home/intrsol/edison-src-16/build_edison/../poky/meta-intel-edison/meta-intel-edison-distro/recipes-support/azure-iot-field-gateway-sdk/azure-iot-field-gateway-sdk.bb, do_configure) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 5664 tasks of which 5660 didn't need to be rerun and 1 failed.
> No currently running tasks (5047 of 5676)
> 
> Summary: 1 task failed:
>   /home/intrsol/edison-src-16/build_edison/../poky/meta-intel-edison/meta-intel-edison-distro/recipes-support/azure-iot-field-gateway-sdk/

Has there been any changes which i have to make ?

**Comment by darobs** [comment]
In order to get a better idea of what went wrong, could you attach `deps/ctest/build/error.txt` and `deps/ctest/build/output.txt`? That will give me a lot of information.

I'll also be trying this myself, so I'll let you know if I run into any trouble and how I fixed it.

**Comment by gerrik84** [comment]
error.txt is empty....

output.txt:

> Scanning dependencies of target ctest
> [100%] Building C object CMakeFiles/ctest.dir/src/ctest.c.o
> Linking C static library libctest.a
> [100%] Built target ctest
> Install the project...
> -- Install configuration: ""
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/lib/libctest.a
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/include/ctest.h
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/include/ctest_macros.h
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/cmake/ctestTargets.cmake
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/cmake/ctestTargets-noconfig.cmake
> -- Installing: /home/intrsol/azure-iot-gateway-sdk/install-deps/cmake/ctestConfig.cmake

**Comment by darobs** [comment]
OK, so it looks like ctest built correctly, but failed when installing it to the local "install-deps" directory, or at least the command returned a non-zero value.  I'll run it myself to see what I get.

**Comment by gerrik84** [comment]
ok thanks

**Comment by darobs** [comment]
I'm still working on this, and I _think_ the bitbake recipe needs to be updated, but getting a system set up and running bitbake is going slowly for me.

I did realize we have a wealth of information from our Intel counterparts, where they publish their patches and adjustments to the Azure-IoT-Gateway.
Please check out  https://github.com/intel-iot-devkit/meta-iot-cloud/tree/master/recipes-azure/azure-iot-gateway-sdk 
This is for Yocto in general, not specifically for Edison, but it may help in the meantime.

**Comment by darobs** [comment]
Hi @gerrik84 , I'm still working on this. I can see the same error you do when I use our example bitbake file. This file wasn't updated when we made several changes to the build, as we've been cross-compiling when targeting the Edison.

While looking at this issue, I've discovered the way the Intel people have done it makes much more sense, and if you can successfully incorporate their recipes, I think that would be the best way forward.  I will share the changes when I get a working image. 

Thanks for your patience,

**Comment by darobs** [comment]
Now that I have the Intel recipes working, my recommendation stands.  Intel has done a very good job of providing bitbake recipes that work with the azure SDKs.

My steps:
```
cd /path/to/iot-devkit-yp-poky-edison-20160606/poky
git clone -b master https://github.com/intel-iot-devkit/meta-iot-cloud.git
```
Then I followed the instructions [in the Configuration section of the README](https://github.com/intel-iot-devkit/meta-iot-cloud#Configuration).

After that, I added this line to my conf/local.conf in my build:
```
PACKAGECONFIG_pn-azure-iot-gateway-sdk = "bluetooth"
```
After that I was able to build the edison-image

**Comment by gerrik84** [comment]
thnaks i will try that approach.

**Comment by gerrik84** [comment]
when i try this i get the following error when building the packagegroup-cloud-azure

> WARNING: No recipes available for:
>   /home/intrsol/edison-src-16/build_edison/../poky/meta-intel-iot-devkit/recipes-kernel/linux/linux-yocto-quark_3.8.bbappend
> NOTE: Resolving any missing task queue dependencies
> ERROR: Nothing RPROVIDES 'boost-python' (but /home/intrsol/edison-src-16/build_edison/../poky/meta-iot-cloud/recipes-azure/azure-iot-sdk/python-azure-iot-sdk_1.1.4.0.bb RDEPENDS on or otherwise requires it)
> NOTE: Runtime target 'boost-python' is unbuildable, removing...
> Missing or unbuildable dependency chain was: ['boost-python']
> NOTE: Runtime target 'python-azure-iot-sdk' is unbuildable, removing...
> Missing or unbuildable dependency chain was: ['python-azure-iot-sdk', 'boost-python']
> ERROR: Required build target 'packagegroup-cloud-azure' has no buildable providers.
> Missing or unbuildable dependency chain was: ['packagegroup-cloud-azure', 'python-azure-iot-sdk', 'boost-python']

**Comment by darobs** [comment]
I get the same thing when I attempt to make everything in `recipes-azure`, and `python-azure-iot-sdk `in particular.  I only added the gateway (`azure-iot-gateway-sdk`) recipe, which isn't dependent on the `python-azure-iot-sdk ` recipe.

i.e.:
`meta-intel-edison/meta-intel-edison-distro/recipes-core/images/edison-image.bb:IMAGE_INSTALL += "azure-iot-gateway-sdk"`

**Comment by damonbarry** [comment]
PR #132 updated our documentation to recommend using the Azure recipes from Intel, and removed our bitbake file. Please let us know if the [new instructions](https://github.com/Azure/azure-iot-gateway-sdk/blob/aa580c17f35d9f34cb079bd90ee60b540b360774/samples/simulated_device_cloud_upload/README.md#yocto-linux-and-intel-edison) don't work for you. Thanks!

**Comment by gerrik84** [comment]
Thanks i will check that later today.

**Comment by gerrik84** [comment]
Thanks that worked for me.

**Comment by damonbarry** [comment]
Fix is in the [2017-03-06](https://github.com/Azure/azure-iot-gateway-sdk/tree/2017-03-06) release.
