### ISSUE TITLE
failed to prepare environment for node

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-gateway-sdk#111]
trying to follow the instructions on the nodejs_simple_sample README. 
No joy. Like that:
----------------------------------------------------------------------------------------------------------------------
warning: unable to access 'deps/npm/node_modules/node-gyp/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/code-point-at/node_modules/number-is-nan/.gitattributes': Filename too long
fatal: cannot create directory at 'deps/npm/node_modules/node-gyp/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan': Filename too long
warning: Clone succeeded, but checkout failed.
'vcbuild.bat' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

disclaimer. I am a wndows newbie (noob?) and have no idea why vcbuild is nowhere in my laptop. I have searched around for vcbuild.bat and got scary stuff like https://github.com/nodejs/node-gyp/issues/629 and i remain clueless. so i apologize in advance if this is just something that i should know but don't, but nevertheless would appreciate guidance.

**Comment by avranju** [comment]
I am guessing you're running into the [Windows maximum path length](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) issue. Do you think you could attempt cloning the repo in the root of a drive? For example: **c:\azure-iot-gateway-sdk**?

**Comment by lucarv** [comment]
i put it in a ubuntu VM, still not working but at least i don't have the long path issue anymore

**Comment by damonbarry** [comment]
@lucarv Can you post the output from your Ubuntu VM (including the command you issued)?

**Comment by damonbarry** [comment]
If you are seeing something on Windows other than the max path length issue (which is simply a hard limitation in Windows--nothing for us to do about it), please reopen with details. Thanks!
