### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-gateway-sdk#112]
just running the simple_sample example, got this:

Gateway is running. Press return to quit.
printer.receive - 36, 18
Segmentation fault (core dumped)

repeatedly....clues?

**Comment by damonbarry** [comment]
@lucarv I assume #111 is no longer an issue if you are able to run the Node.js sample?

Let's figure out what's happening here. Can you give us a little more information? Specifically:
- The git commit ID you are currently sync'd to in your local repo
- Your operating system & version
- The full output when you run the sample (including the command you issued)

Thanks!

**Comment by zafields** [comment]
Hi guys,

I just made sure my Ubuntu was fully up to date and started with fresh clone of `https://github.com/azure/azure-iot-gateway-sdk/` (master branch). I ran through all the steps in our sample, but I was unable to reproduce this error.

I am using these versions:
node v7.4.0
python v2.7.12

@lucarv Can you share version information from your configuration?

**Comment by lucarv** [comment]
@damonbarry:
#111 still an issue, i just moved to linux as i am pressed for time
<git commit ID>
tree b123a25d47ab4130931f8948ce74c6b7ad41f163
parent 05c98e0ed7c1f06c9baebbbd43d7b207e561ebbd
parent ba14c79687fb9ddf42ac408d68c37f7b76f4a45b
author Azure IoT Builder <azioclb@microsoft.com> 1485560441 +0000
committer Azure IoT Builder <azioclb@microsoft.com> 1485560441 +0000

<OS>
Ubuntu 14.04.4 LTS
kernel: 3.13.0-32-generic
NOTE: running on a parallels VM inside a MAC Sierra

<command>
<1st run>
parallels@ubuntu:~/dev/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample$ ./nodejs_simple_sample ../../../samples/nodejs_simple_sample/src/gateway_sample_lin.json
<result>
Gateway is running. Press return to quit.
printer.receive - 36, 18
Segmentation fault (core dumped)
<2nd up to 5th run>
parallels@ubuntu:~/dev/kth/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample$ ./nodejs_simple_sample ../../../samples/nodejs_simple_sample/src/gateway_sample_lin.json
Gateway is running. Press return to quit.
Segmentation fault (core dumped)

@zafileds:
node 6.9.4
python 2.7.6

**Comment by lucarv** [comment]
quick update, i have moved out from the parallels vm and deployed on a physical box, exact same config and the problem disappeared. i will not investigate this further, but could it be a problem caused by the hypervisor itself???

**Comment by avranju** [comment]
I did a test with Docker on macOS and it worked fine. Docker for Mac runs the Docker engine in a Linux VM using macOS's native [hypervisor](https://developer.apple.com/reference/hypervisor). So yes, this is likely a problem with the virtualization of some system call on Parallels.
