### ISSUE TITLE
Build fails with --run-unittests enabled

### ISSUE THREAD

**Issue by 606simps** [Azure/azure-iot-gateway-sdk#116]
Hi,

I tried to build the Gateway 2017-01-13 version with --run-unittests enabled on a Windows 10 64bits machine. I got the following errors. The build worked fine without --run-unittests enabled. Please advise. Thanks!

       "D:\code\azure-iot-gateway-sdk_0113\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tests\ble_ut\ble_ut_exe.vcxproj.metaproj" (default target) (16) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tests\ble_ut\ble_ut_exe.vcxproj" (default target) (114) ->
         D:\code\azure-iot-gateway-sdk_0113\modules\ble\tests\ble_ut\ble_ut_windows.cpp(10): fatal error C1083: Cannot open include file: 'micromock.h': No such file or directory [D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tes
       ts\ble_ut\ble_ut_exe.vcxproj]

       "D:\code\azure-iot-gateway-sdk_0113\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tests\ble_ut\ble_ut_dll.vcxproj.metaproj" (default target) (15) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tests\ble_ut\ble_ut_dll.vcxproj" (default target) (115) ->
         D:\code\azure-iot-gateway-sdk_0113\modules\ble\tests\ble_ut\ble_ut_windows.cpp(10): fatal error C1083: Cannot open include file: 'micromock.h': No such file or directory [D:\code\azure-iot-gateway-sdk_0113\build\modules\ble\tes
       ts\ble_ut\ble_ut_dll.vcxproj]

       "D:\code\azure-iot-gateway-sdk_0113\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_exe.vcxproj.metaproj" (default target) (38) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_exe.vcxproj" (default target) (93) ->
       (Link target) ->
         LINK : fatal error LNK1104: cannot open file 'micromock_ctest.lib' [D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_exe.vcxproj]

       "D:\code\azure-iot-gateway-sdk_0113\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_dll.vcxproj.metaproj" (default target) (37) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_dll.vcxproj" (default target) (122) ->
         LINK : fatal error LNK1104: cannot open file 'micromock_cpp_unittest.lib' [D:\code\azure-iot-gateway-sdk_0113\build\core\tests\gwmessage_ut\gwmessage_ut_dll.vcxproj]

       "D:\code\azure-iot-gateway-sdk_0113\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj.metaproj" (default target) (23) ->
       "D:\code\azure-iot-gateway-sdk_0113\build\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj" (default target) (98) ->
       (ClCompile target) ->
         D:\code\azure-iot-gateway-sdk_0113\core\src\module_loaders\dynamic_loader.c(137): error C2440: 'initializing': cannot convert from 'MODULE_LIBRARY_HANDLE' to 'DYNAMIC_MODULE_HANDLE_DATA *' [D:\code\azure-iot-gateway-sdk_0113\bu
       ild\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj]
         D:\code\azure-iot-gateway-sdk_0113\core\src\module_loaders\dynamic_loader.c(150): error C2440: 'initializing': cannot convert from 'MODULE_LIBRARY_HANDLE' to 'DYNAMIC_MODULE_HANDLE_DATA *' [D:\code\azure-iot-gateway-sdk_0113\bu
       ild\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj]
         D:\code\azure-iot-gateway-sdk_0113\core\src\module_loaders\dynamic_loader.c(313): error C2059: syntax error: '.' [D:\code\azure-iot-gateway-sdk_0113\build\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj]
         D:\code\azure-iot-gateway-sdk_0113\core\src\module_loaders\dynamic_loader.c(325): error C2143: syntax error: missing ';' before '}' [D:\code\azure-iot-gateway-sdk_0113\build\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vc
       xproj]
         D:\code\azure-iot-gateway-sdk_0113\core\src\module_loaders\dynamic_loader.c(325): error C2059: syntax error: '}' [D:\code\azure-iot-gateway-sdk_0113\build\core\tests\dynamic_loader_ut\dynamic_loader_ut_dll.vcxproj]

Stephen

**Comment by aribeironovaes** [comment]
Hi Stephen,

Try deleting the install deps folder and running the command again.

Thanks

Angelo Ribeiro

**Comment by 606simps** [comment]
Hi Angelo,

Thanks, problem solved. Any guess of the reason causing this? I only built .net and c modules.

Thanks,
Stephen

**Comment by aribeironovaes** [comment]
Yes, you probably have built it before without the --run-unit-test option. 
When we do that we don't build tests dependencies on our deps. 

One mitigation that we did was to add the option to rebuild the dependencies... 

But we were discussing today that it would be good to have a way to detect of tests dependencies were built or not.

Glad it worked for you.

Thanks,

Angelo Ribeiro

**Comment by 606simps** [comment]
Thanks for the clarification.
Stephen
