### ISSUE TITLE
Can AMQP and MQTT protocols be used?

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-iot-gateway-sdk#12]
Can AMQP and MQTT protocols be used for Gateway communication with Azure IoT Hub? At the moment only HTTP transport is provided in the samples.

**Comment by darobs** [comment]
Thanks for the question, @tedvanderveen. We provided a sample for the HTTP transport because multiple IoTHub devices may use a shared HTTP transport (i.e. we only establish one TLS connection).   AMQP and MQTT may also be used, but each device instance will create its own transport.

As shared transports become available for the other protocols, we will update the samples to include them.

**Comment by tedvanderveen** [comment]
Thanks @darobs. Does it use Secure WebSockets (over TLS) to ensure cloud-to-device communications through firewalls etc and bi-directional support?

**Comment by damonbarry** [comment]
@tedvanderveen Yes, I believe the IoT Hub messaging SDK supports AMQP and MQTT over websockets, although as mentioned we don't have sample _gateway_ modules yet for these protocols.

**Comment by darobs** [comment]
Expanding on Damon's answer: Yes, the IoT-Device-SDK can use TLS for the WebSockets communication, and it is bi-directional.
Here is the code that shows that:
https://github.com/Azure/azure-iot-sdks/blob/develop/c/iothub_client/src/iothubtransportamqp_websockets.c, line 14
That “true” on the configuration is to set WSIO_CONFIG->use_ssl, which enables WebSockets over SSL down on uamqp layer.

The documentation we have about support is this:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-tested-configurations/ 
however it doesn’t mention the fact that we use SSL for WebSockets connections.

Other related docs:
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/amqp-c-websockets-run-sample.md

What we don't currently have is a gateway module for that protocol.

**Comment by darobs** [comment]
If you check out the latest master release, the ability to specify AMQP and MQTT as the protocol has been added to the iothub module.  We haven't added the support for a shared AMQP transport, as we are still waiting on the SDK support for this.

**Comment by chipalost** [comment]
I'm closing this issue as I believe it's been resolved.
