### ISSUE TITLE
"make" command doesn't re-compile modified source file

### ISSUE THREAD

**Issue by GrantEdwards** [Azure/azure-iot-gateway-sdk#121]
When I modify a C source file (e.g. deps/c-utility/adapters/httpapi_curl.c),
and then do a "make" in the build directory, that source file does not get re-compiled.

Running ./tools/build.sh also does not re-compile the file.

Removing the library file that contains the code from httpapi_curl.c
(install-deps/lib64/libaziotsharedutil.so) also fails to re-compile
the file:

    $ make
    [  3%] Built target parson
    [ 22%] Built target gateway_static
    make[2]: *** No rule to make target '../install-deps/lib64/libaziotsharedutil.so', needed by 'core/libgateway.so'.  Stop.
    make[1]: *** [CMakeFiles/Makefile2:1023: core/CMakeFiles/gateway.dir/all] Error 2
    make: *** [Makefile:139: all] Error 2

**Comment by GrantEdwards** [comment]
The only way I've found to make sure modified source files get compiled is to run build.sh
for a different target architecture, and then re-run it for the desired target architecture.

**Comment by damonbarry** [comment]
Run the gateway SDK's build.sh with the `--rebuild-deps` option, or manage dependencies manually.
