### ISSUE TITLE
Suggestion: print useful curl error messages.

### ISSUE THREAD

**Issue by GrantEdwards** [Azure/azure-iot-gateway-sdk#122]
The current httpapi_curl.c just prints "Error" when a curl call fails.

That's not very useful.

Attached is a patch that shows how you print out useful curl error
messages.

**Comment by GrantEdwards** [comment]
Ah, you're not allowed to attach files with a suffix of .patch.  I've renmed it.
[httpapi_curl-useful-error-message.patch.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/755154/httpapi_curl-useful-error-message.patch.txt)

**Comment by damonbarry** [comment]
It would be great if you could file a pull request in the [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility) repo for this. I'd do it on your behalf, but if you're contributing code you need to sign the CLA.
