### ISSUE TITLE
Handle network connectivity issues

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/azure-iot-gateway-sdk#13]
How does the Gateway SDK handle IP connectivity or Azure IoT Hub availability issues?
In case Message delivery fails, should the message be re-published to the Bus? What is the preferred way to implement a delay between connection retries?

**Comment by darobs** [comment]
Hi @tedvanderveen, thanks for your question.  At this time, for short-term connectivity issues, we are relying on the IoT-Device-SDK's queueing mechanism.  

However , this won't survive a gateway shutdown or catastrophic failure. We recognize this as a need, and it's in our backlog to address.

**Comment by damonbarry** [comment]
>How does the Gateway SDK handle IP connectivity or Azure IoT Hub availability issues?

We rely on the retry behavior of the device SDK. They're currently working on retry and exponential backoff, so the gateway will benefit from those features when they come in.

>In case Message delivery fails, should the message be re-published to the Bus?

Some scenarios might need this sort of thing, others won't. We don't currently do this.

>What is the preferred way to implement a delay between connection retries?

Again, the device SDK is working on this, and I believe they plan to expose a way to configure retries. (see  [this project on the device SDK's repo](https://github.com/Azure/azure-iot-sdks/projects/2))
