### ISSUE TITLE
CMake failure when running the "build.cmd" from the /tools dir.

### ISSUE THREAD

**Issue by AshleyPak8** [Azure/azure-iot-gateway-sdk#131]
C:\azure-iot-gateway-sdk\tools>build.cmd
Cleaning up build artifacts...
The system cannot find the file specified.
***Running CMAKE for Win32***
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
See also "C:/azure-iot-gateway-sdk/build/CMakeFiles/CMakeError.log".

C:\azure-iot-gateway-sdk\tools>

Do I have to install the C compiler and the CXX coompiler?

**Comment by darobs** [comment]
Hello @AshleyPak8, yes, for Windows, you do need to have the Visual C++ option installed for Visual Studio.  We are currently expecting VS 2015 (i.e. version 14).

If you already have that installed, then the most likely problem is that you're running it in a regular command window.  If that's the case, try running the build command in a "Developer Command Prompt."

Beyond that, I'll need to do some more serious debugging, probably starting with those CMakeOutput.log and CMakeError.log.

Thanks for your interest!
Dave Robson

**Comment by AshleyPak8** [comment]
HI @darobs , I have the following installed:

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA042
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-40000-00000-AA042
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA042
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA042
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.17.00119.9
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20907.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

________________________________________________________________________________________________________

I was running in the "Developer Command Prompt".

Here is the CMakeOutput.log and CMakeError.log.

CMakeError.log:
______________________________________________________________________________________________________

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/12/2017 8:34:24 PM.
Project "C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdC\CompilerIdC.vcxproj]
  
  
Done Building Project "C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.24


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/12/2017 8:34:25 PM.
Project "C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdCXX\CompilerIdCXX.vcxproj]
  
  
Done Building Project "C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\azure-iot-gateway-sdk\build\CMakeFiles\3.7.2\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.23


______________________________________________________________________________________________________________
CMakeOutput.log
__________________________________________________________________________________________________________
The system is: Windows - 6.1.7601 - AMD64



Thank for the help!

-Ashley

**Comment by darobs** [comment]
I have cl.exe in"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe" which is part of my PATH in a developer prompt.  If you've installed VC++, cl.exe should be in VC\BIN of the install folder.

I suspect that Visual Studio lost track of where the compiler is.

I found [this ](https://blogs.msdn.microsoft.com/deva/2015/03/24/after-migration-vs-2013-c-project-throws-error-trk0005-failed-to-locate-cl-exe-the-system-cannot-find-the-file-specified/)which looks pretty similar to your error:

>If there is no cl.exe in the directory, then either you can repair or reinstall Visual Studio.

I'd try repairing the install first, but there are other options given on that page.

(I have a fresh install of VS2015 on this PC, so I can't confirm this.)

**Comment by damonbarry** [comment]
@AshleyPak8 in the *same* command prompt that you used above, what output do you get if you run the command `where cl`? Here's what I get:

![where-cl](https://cloud.githubusercontent.com/assets/9042469/22897220/ce90f4c2-f1d7-11e6-91a3-4cc240b9c744.png)

**Comment by AshleyPak8** [comment]
@damonbarry & @darobs 

@darobs was correct, i was missing the C+ compiler from install. Once I install the right compiler, I had no issues in using CMAKE to compile the .dlls and directories I needed.

Thank you for your support. I am sure I will be back for more:)

Regards

-Ashley
