### ISSUE TITLE
Build sdk with .net binding on a device running windows 10 iot core (related to Issue #86)

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-gateway-sdk#143]
Following our previous communication regarding Issue 86 and as we are working now on IoT gateway SDK, I have to build modules for IoT Gateway in .NET on a device running windows 10 iot core. I suppose that I can't follow the instructions written in https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/dotnet_binding_sample/README.md, i.e run tools\build_dotnet.cmd and then run tools\build.cmd --enable-dotnet-binding.

I would really appreciate your help.
Maria.

**Comment by aribeironovaes** [comment]
Hi Maria, 

Did you try running https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/dotnet_core_module_sample/README.md? 

Also, what it your Device? Do you know if it is x86 or x64? Right now we have known issue with .NET Core on x86, it's working for x64 and for Linux. 

Let us know, 

Angelo Ribeiro.

**Comment by mtheolog** [comment]
Hi Angelo,
Our device is a dragonboard 410c (ARM) that runs windows 10 iot core and in order to build and deploy the gateway on it, I followed the steps described in Issue 86 and not the generic build process described in your documentation. Actually, I built the gateway for ARM by letting cmake generate the ARM flavored Visual Studio projects (as specified in Issue 86) and then I deployed it to Windows IoT Core device and set up VS remote debugger by following the http://www.seanliming.com/Docs/Articles/IoT10Core/Windows-10-IoT-Core-Native-Remote-Debug-V1.3.pdf document (recommended in Issue 86).

Thus, I wonder whether the generic build commands described in https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/dotnet_core_module_sample/README.md can build ARM flavored VS projects.
Regards,
Maria.

**Comment by aribeironovaes** [comment]
Hi Maria, 

I honestly don't know. AFAIK, .NET Core is not officially supported in ARM (I may be wrong), but I did see some people (and this is the beauty of an open community! :)) building .NET Core on Arm. 

That said, assuming you got already gateway building on your gateway what you should do would be: 
1-Making sure you have .NET Core built for ARM; 
2-Get the location where you have your .net core change the .JSON File on the sample; 
3-With that you would have a .NET Core Module Running! 

This is the 1st step. This scenario would be a native gateway being able to load .NEt Core Modules on ARM. If you want your gateway to be a .NET Core Gateway I'm working on a change right now that will allow you to have a .NET Core Gateway to load .NEt Core modules. 

Again, try it out and please, do report if you find any problem. And you can even contribute back with some type of documentation teaching us how you did? 

If I know someone that succeeded on this area I will also let you know. 

Thanks for Using our Gateway SDK!

Cheers, 

Angelo Ribeiro.
