### ISSUE TITLE
I try to below command, but error occurred

### ISSUE THREAD

**Issue by maccence** [Azure/azure-iot-gateway-sdk#155]
I try to below command, but error occurred

build.cmd --enable-dotnet-binding
 But I found this error in the cmakeError notepad

Build flags: 
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 09/03/2017 19:41:01.
Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.51

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 09/03/2017 19:41:02.
Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\CMakeCXXCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj]
Done Building Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\3.8.0-rc2\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.61

I think it is because of the path of the ucrtd.lib. When I launch the execution of the command, it generates a compilerIdc project without an additional dependencies or a path for ucrtd.lib.

Can someone help me?

**Comment by damonbarry** [comment]
Sorry...what command did you try? And what exactly was the error?

**Comment by maccence** [comment]
Hi Damonbarry, I am sorry You can find now my error. I just posted it

**Comment by damonbarry** [comment]
I see that you're using Visual Studio 2015, and it looks like CMake is able to find the compiler and linker--that's good.

ucrtd.lib comes from the Windows SDK. I wonder if you upgraded from an earlier version of Visual Studio, and perhaps you don't have the right version of the Windows SDK installed?

What version of VS 2015 do you have? Is it Update 3, or something else?

If you do an internet search for "ucrtd.lib" you'll find that lots of people have had this same problem (`LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'`), and there are various solutions to try.

**Comment by maccence** [comment]
I did an Internet search and the solution is to open visual studio and define the ucrtd.lib path for the project to build. But for me, its different. When I launch the command build.cmd --enable-dotnet-binding, the project compilerIdc is generated automatically without ucrtd path (I checked this, the path is empty) so the problem here is how to make the command generate the project with the right path to complete the execution?

**Comment by damonbarry** [comment]
Right, the solutions I saw had to do with (re)installing the right Windows SDK, or repairing your VS install.

What version of VS2015 do you have? And did you upgrade from a previous version, or was this a fresh install?

**Comment by maccence** [comment]
How to know the version of the visual studio 2015? it is a fresh install

**Comment by maccence** [comment]
But the problem is that the project "CompilerIdc" is generated without a path for ucrtd.lib so the execution is interrupted before enabling the building. I don't know what happened for those who used the same command ?

**Comment by maccence** [comment]
This picture shows the configuration of the project additional dependencies.
As you see there is not a path.
![2017-03-09 22_50_04-compileridc - microsoft visual studio](https://cloud.githubusercontent.com/assets/26273323/23772372/03b96638-051b-11e7-9dd4-b701f76f72b8.png)

**Comment by damonbarry** [comment]
If you go to "Help" on the VS2015 menu, then select "About" it will show you the version.

Certain libraries, specifically in the C/C++ runtime and Windows SDK, may not need explicit paths--Visual Studio checks certain paths implicitly. So it's not surprising that you don't see the path. You can go to the Project Properties and select "VC++ Directories" to see the implicit paths that Visual Studio is scanning. In my project, here are the values for "Library Directories":

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib
>>> C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x86 <<<
C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\lib\um\x86
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x86
```

Since I have a copy of ucrtd.lib under "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\ucrt\x86", I don't see the problem you're seeing.

The CompilerIdc project is what CMake uses to make sure it can access everything it needs for your compiler. Since the project fails, CMake concludes that the something's wrong with the environment, and exits.

Another question: What's the title of the Command Prompt window where you ran `build.cmd`? It should be "Developer Command Prompt for VS2015" (which will have all the right environment settings for using Visual Studio from the command line).

**Comment by maccence** [comment]
Thank you for the help.
Yes I am using Developer Command Prompt for VS2015.

Now, I will copy the ucrtd.lib to the one of the scanned paths by visual studio. Do you recommend that from me?

**Comment by maccence** [comment]
or I change the scanned path by the right ones?

**Comment by damonbarry** [comment]
I wouldn't copy ucrtd.lib.

First, I would look at your "Library Directories" setting in VS. Do you have something similar to "C:\Program Files (x86)\Windows Kits\10\lib\10.0.xxxxx.0\ucrt\x86"? If so, what is it exactly? And do you have that folder on your filesystem?

I suspect you may end up (1) installing the latest Windows 10 SDK, and (2) perhaps updating your "Library Directories" (or maybe repairing your VS install). But this is getting into areas where I am not expert...

**Comment by maccence** [comment]
In my system folder, I have a path similar to C:\Program Files (x86)\Windows Kits\10\lib\10.0.xxxxx.0\ucrt\x86" but no one of the scanned paths by VS is similar to this. The paths take to other folder which doesnt contain ucrtd.lib .

**Comment by maccence** [comment]
These are the paths scanned by Visual Studio

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib
C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\mfc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include

But the ucrtd.lib is in the windows kits folder.

**Comment by maccence** [comment]
I resolved this problem by adding the ucrtd.lib to one of the scanned paths.
Now, I have another problem. This is what I found in the CmakeEroor notepad file:

Determining if the _M_AMD64 exist failed with the following output:
Change Dir: C:/Users/ymlaouhia/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_cd389.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 10/03/2017 11:28:42.

Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_cd389.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_cd389.dir\Debug\".

  Creating directory "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_cd389.dir\Debug\cmTC_cd389.tlog\".

InitializeBuildStatus:

  Creating "cmTC_cd389.dir\Debug\cmTC_cd389.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_cd389.dir\Debug\\" /Fd"cmTC_cd389.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_cd389.dir\Debug\\" /Fd"cmTC_cd389.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  

  CheckSymbolExists.c

C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_cd389.vcxproj]

Done Building Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_cd389.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_cd389.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_cd389.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.99


File C:/Users/ymlaouhia/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_AMD64
  return ((int*)(&_M_AMD64))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Is this a problem related to the scanned path again or it is another problem? Thank you.

**Comment by damonbarry** [comment]
If you search our closed issues for `_M_AMD64` you'll see that several people have hit this issue. In nearly every case, it's because they weren't running the command inside a "Developer Command Prompt for VS2015". You may also want to pass the `--rebuild-deps` flag to our build.cmd, in case your dependencies are in a weird state.

**Comment by maccence** [comment]
But I am using The developer command prompt for VS2015.
How can I pass the --rebuild-deps flag to the build.cmd?

**Comment by damonbarry** [comment]
Your original command line: `build.cmd --enable-dotnet-binding`
...becomes: `build.cmd --enable-dotnet-binding --rebuild-deps`

**Comment by maccence** [comment]
It is better  now. Some errors are corrected but I still have an error.
 This is the cmake error notepad: (and I attached the command prompt with the comment)

Determining if the _M_AMD64 exist failed with the following output:
Change Dir: C:/Users/ymlaouhia/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_9b204.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 10/03/2017 19:55:25.

Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_9b204.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_9b204.dir\Debug\".

  Creating directory "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_9b204.dir\Debug\cmTC_9b204.tlog\".

InitializeBuildStatus:

  Creating "cmTC_9b204.dir\Debug\cmTC_9b204.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9b204.dir\Debug\\" /Fd"cmTC_9b204.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9b204.dir\Debug\\" /Fd"cmTC_9b204.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  

  CheckSymbolExists.c

C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_9b204.vcxproj]

Done Building Project "C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_9b204.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_9b204.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Users\ymlaouhia\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_9b204.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.62


File C:/Users/ymlaouhia/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_AMD64
  return ((int*)(&_M_AMD64))[argc];
#else
  (void)argc;
  return 0;
#endif
}

![2017-03-10 19_59_11-developer command prompt for vs2015](https://cloud.githubusercontent.com/assets/26273323/23808974/1dccc978-05cc-11e7-86bb-a8c9c6417d90.png)

**Comment by damonbarry** [comment]
Can you attach `deps\ctest\build\error.txt` and `deps\ctest\build\output.txt`?

**Comment by maccence** [comment]
The error file is empty and this is the output file
[output.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/834996/output.txt)

**Comment by damonbarry** [comment]
ctest is the very first dependency we try to build prior to building the gateway SDK itself. And while trying to build ctest, your compiler quickly runs into this error:
```
fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
```
stdio.h is a core header of the C runtime, so if your compiler can't find that you're in trouble. 😮 

It really looks to me like there's something wrong with your Visual Studio install, and I'm not sure how to fix it. If I were you, I'd uninstall any Windows SDKs and Visual Studio, then reinstall them.

**Comment by maccence** [comment]
Thank you very much, i'll do as you said and i'll let you updated. Thanks again

**Comment by damonbarry** [comment]
@maccence Great! I'll close this for now...please reopen if needed. Thanks!
