### ISSUE TITLE
Exception while closing gateway

### ISSUE THREAD

**Issue by AdamMachera** [Azure/azure-iot-gateway-sdk#161]
I'm creating gateway from c# using those function

        [DllImport("gateway.dll", CharSet=CharSet.Ansi, EntryPoint = "Gateway_CreateFromJson", CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr GatewayCreateFromJson([MarshalAs(UnmanagedType.LPStr)] string filePath);
        [DllImport("gateway.dll", EntryPoint = "Gateway_Destroy", CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr GatewayDestroy(IntPtr gateway);

Gateway is using nodejs and c# modules.
From time to time if I try to close gatewat I'm getting exception from node.cc
Bolded code throws exception: 

_Unhandled exception at 0x00007FF8F5016DF0 in IoTClient.exe: 0xC0000005: Access violation executing location 0x00007FF8F5016DF0._

    if (instance_data->use_debug_agent())
      EnableDebug(env);

    {
      SealHandleScope seal(isolate);
      bool more;
      node::node_loop_func loop_func = instance_data->loop_func();
      do {
        if(loop_func != NULL) {
          loop_func(isolate);
        }
        **v8_platform.PumpMessageLoop(isolate);**
        more = uv_run(env->event_loop(), UV_RUN_ONCE);

        if (more == false) {
          v8_platform.PumpMessageLoop(isolate);
          EmitBeforeExit(env);

          // Emit `beforeExit` if the loop became alive either after emitting
          // event, or after running some callbacks.
          more = uv_loop_alive(env->event_loop());
          if (uv_run(env->event_loop(), UV_RUN_NOWAIT) != 0)
            more = true;
        }
      } while (more == true);
    }

**Comment by avranju** [comment]
This issue is under investigation.

**Comment by avranju** [comment]
I have not been able to reproduce this issue.

**Comment by aribeironovaes** [comment]
Hi @AdamMachera. 
Problem found and PR created to fix this issue.
