### ISSUE TITLE
nodejs_simple_sample does not save data to IoT Hub

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-iot-gateway-sdk#167]
Hi,

I have noticed that the sample does not upload data to IoT Hub. I figured this out by using the Device Explorer tool and monitoring the device which I used to execute the sample.

I particular, I noticed that the `Message` object is being created with empty data on this line:
```js
var m = new Message(message.content ? message.content.buffer : []);
```

Replacing this with the following solves the problem:
```js
var m = new Message(JSON.stringify(message.content));
```

**Comment by darobs** [comment]
Wow, I was able to reproduce this no problem.  I'll fix this and generate a pull request.

**Comment by darobs** [comment]
Merged via commit db4c16

**Comment by aribeironovaes** [comment]
Closing this issue. See last Release.
