### ISSUE TITLE
Error running dotnetcore sample

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-gateway-sdk#176]
When I try running the dotnetcore sample following error is displayed in the console:
![dotnet_core_runtime_error](https://cloud.githubusercontent.com/assets/1545509/24190463/f766a436-0ee8-11e7-85d6-35955887d4fa.PNG)

**Comment by vslepakov** [comment]
build.cmd --enable-dotnet-core-binding --platform x64 and
build_dotnet_core.cmd --config x64

seem to resolve the issue.  the sample is running. seems to be some platform mismatch...

**Comment by aribeironovaes** [comment]
Hi @vslepakov, 

First, thanks for using our Gateway SDK. 
So, you don't need to pass --config x64 on build_dotnet_core.cmd, in fact you don't need to run this script yourself, when you run the script build.cmd --enable-dotnet-core-binding --platform x64 it will already run the build_dotnet_core.cmd. 

That said, from your error message you posted seems that the error was to load the .NET Core CLR. So, if you installed the 64 bit version of the CLR and run the 32bit of the sample, that will happen, so, this is probably why the problem got solve after you build with --platform x64. 

Let us know if we can close this issue, 

Thanks, 

Angelo Ribeiro.

**Comment by damonbarry** [comment]
Closing...please reopen if needed. Thanks!
