### ISSUE TITLE
Error when running 'dotnet_core_managed_gateway'

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-iot-gateway-sdk#177]
The sample 'dotnet_core_managed_gateway' build successfully, but it cannot start. It fails with following exception:

`System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'`

I have installed dotnetcore 1.1.1 setup, which in fact installs v1.0.1.
After that I have copied dotnetcore.dll, gateway.dll and nanomsg.dll to the bin/debug.

**Comment by aribeironovaes** [comment]
Hi @ddobric, Closing this issues since we haven't heard back. 
If you still have problem feel free to reactivate. 
Thanks
Angelo Ribeiro.

**Comment by ddobric** [comment]
The solution was to build with --platform x64.
