### ISSUE TITLE
dotnetcore sample fails to load iothub.dll 

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-gateway-sdk#178]
I extended the dotnet_core_module_sample by addind the identity_map and iothub native modules.
My configuration:

```{
  "loaders": [
    {
      "type": "dotnetcore",
      "name": "dotnetcore",
      "configuration": {
        "binding.path": "dotnetcore.dll",
        "binding.coreclrpath": "C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\1.1.1\\coreclr.dll",
        "binding.trustedplatformassemblieslocation": "C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\1.1.1\\"
      }
    }
  ],
  "modules": [
    {
      "name": "logger",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\logger\\Debug\\logger.dll"
        }
      },
      "args": {
        "filename": "log.txt"
      }
    },
    {
      "name": "IotHub",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\iothub\\Debug\\iothub.dll"
        }
      },
      "args": {
        "IoTHubName": "myhub",
        "IoTHubSuffix": "azure-devices.net",
        "Transport": "amqp"
      }
    },
    {
      "name": "mapping",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\identitymap\\Debug\\identity_map.dll"
        }
      },
      "args": [
        {
          "macAddress": "01:01:01:01:01:01",
          "deviceId": "id",
          "deviceKey": "secret_key"
        }
      ]
    },
    {
      "name": "dotnet_sensor_module",
      "loader": {
        "name": "dotnetcore",
        "entrypoint": {
          "assembly.name": "SensorModule",
          "entry.type": "SensorModule.DotNetSensorModule"
        }
      },
      "args": "module configuration"
    }
  ],
  "links": [
    {
      "source": "*",
      "sink": "Logger"
    },
    {
      "source": "dotnet_sensor_module",
      "sink": "mapping"
    },
    {
      "source": "mapping",
      "sink": "IotHub"
    }
  ]
}```

when I try to run this sample it fails because it cannot load the iothub.dll

![dotnet_core_to_iothub](https://cloud.githubusercontent.com/assets/1545509/24197262/38a06438-0f01-11e7-89b2-1fef91c3a039.PNG)

**Comment by vslepakov** [comment]
...because the iothub_client.dll was missing. it is not really transparent where things come from.

**Comment by aribeironovaes** [comment]
Hi @vslepakov , 

Thanks for your feedback. So, after copying the iothub_client.dll did you get your sample to run? 

So, these are just sample, but if you want to integrate them (Adding iothub and identitymap modules together with .NET Core Sensor and Printer module) you have to also make sure you have all the dependencies copied/generated. 

If you take a look into simulated_device_cloud_upload sample (which uses iothub and identitymapmodules), they copy all the dependencies on their Cmake File (Check here: https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/simulated_device_cloud_upload/CMakeLists.txt). 

So, the commands linkSharedUtil, LinkHTTP and copy_iothub_client_dll are necessary if you want to use automated build (using CMAKE). Of course you can always copy manually if you are just testing. 

Let me know if this helps and if your problem got solved, 

Thanks, 

Angelo Ribeiro.

**Comment by vslepakov** [comment]
Hi @aribeironovaes ,

thanks for your reply, yes after copying the iothub_client.dll it just worked.
It is ok to copy dependencies around manually or using CMake, the problem is just that one does not really know what needs to be copied where and why. 

As you pointed out, we used the simulated_device_cloud_upload sample to compare it to the dotnet_core_module_sample in order to figure out what is actually different. The iotub native module's devdoc does not really specify all dependencies to be copied so it can function correctly. 
It is very implicit.

What would be the recommended way to just generate the gateway executable outside of any samples so it can be extended by modules using the json config?

Regards
Vitaliy Slepakov

**Comment by aribeironovaes** [comment]
Thanks @vslepakov , 

Good feedback. We could add on that document the list of dependencies needed for that module, although the list is added on the CMakeFile. 

So, not sure I understood your question regarding generating the gateway executable outside of any sample... 
If you take actually a closer look into our samples, the only difference between them are the Cmake Files (Copying the dependencies.) and the .JSON Configuration file.... We just separate them so we can create a Specific Readme file explaining how to run that specific sample.. 

So, i would say if you want to build your own gatewy sample, just make sure you know the dependencies of the modules you are adding and package it accordingly. 

Hope this helps and let me know if you need us to addressing something on this issue or if we can ahead and close it. 

Thanks again, 

Angelo Ribeiro.

**Comment by vslepakov** [comment]
Hi @aribeironovaes ,

Thanks for the information, I appreciate it.

Best Regards 
Vitaliy Slepakov
