### ISSUE TITLE
byte array is not a gateway message serialization

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-iot-gateway-sdk#19]
Getting this error after I hit enter when hello_world sample is running.

`/consolelogger.c Func:consolelogger_log Line:31 byte array is not a gateway message serialization`

**Comment by darobs** [comment]
Thanks @jonbgallant. This is a known problem which we are working towards resolving.  It does not affect the function of the gateway, but it is an annoyance that we're receiving it. The current PubSub message bus implementation is not complete and this is a side effect of that.  I added a task in the current PBI to ensure this is resolved in the next sprint.

**Comment by darobs** [comment]
The latest commit on develop does not generate this annoyance message.
