### ISSUE TITLE
.Net Core Module Microsoft.Azure.Devices.Gateway.dll can't be added to references

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/azure-iot-gateway-sdk#196]
Hi Guys,

I´m trying to build my own Core module. I used the dotnet_core_module_sample example. Here "Creating your own module" says "Add Reference to Microsoft.Azure.Devices.Gateway DLL."
I have a problem adding exactly that Microsoft.Azure.Devices.Gateway.dll. When trying to add this to references I get the following Error:

> .NET Core projects only support referencing .NET framework assemblies in this release. To reference other assemblies, they need to be included in a NuGet package and reference that package. 

Unfortunately I don't know how to include this dll in a NuGet package. Is that really necessary? There was no word about this in the description.
Thanks

**Comment by aribeironovaes** [comment]
HI @Zuendelmeister , 
So, hand in there regarding the Nuget Package. We will have a nuget package soon for .NET Core. 
Regarding how to add, Microsoft.Azure.Devices.Gateway DLL, you should add the project or, in case of Linux, add the Microsoft.Azure.Devices.Gateway project as a dependency. 
I believe on .NET Core you can't add a Managed DLL directly into your project.. 

Try to do the samething we do in our solution file (adding the project) and let us know. 

Thanks, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @aribeironovaes,
thank you so much for your answer. I was a little confused because the documentatin told me to add the dll reference. Now I opened your solution and created a new Dotnet Core module under "Modules". This seems to work quite fine. 
I´m getting an error though. 
MSB4019	The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	FirstCoreModule	C:\Projects\AzureGitCoreModule\FirstCoreModule\FirstCoreModule.xproj	8	
But i guess this is due to a wrong dotnet core installation. I look into this tomorrow.
Thanks again, keeping you updated.

Best regards Zuendelmeister

**Comment by Zuendelmeister** [comment]
Ok now it works. Had to add a global.json
For everyone having the same issue:

> {
  "sdk": { "version": "1.0.0-preview2-1-003177" }
}
 After that I had another issue with a missing lock file. Solution war to cd to the project folder (where the global.json is) und use this command:

> dotnet restore

I hope this helps. Best regards
Zuendelmeister

**Comment by aribeironovaes** [comment]
Hi @Zuendelmeister, 

So, quick question. Did you follow this doc and got  the sample working, before you add your module? 
https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/dotnet_core_module_sample/README.md

Another suggestion that you can that you can follow is to use our newly created Nuget Package for Module Development: 
https://www.nuget.org/packages/Microsoft.Azure.Devices.Gateway.Module/

Other question, any reason why you are using the version :1.0.0-preview2-1-003177 instead of the latest .NET Core 1.1.1?

Try the Nuget package and let us know if it works.  (Just be mindfull that this specific version of .NET Core Nuget is 32 bit, so you need to install latest version of .NET core 32 bits...) A 64 bit package is being generated. 

Thanks, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi again @aribeironovaes 

thanks for your response. To your first question: Yes I used this tutorial. And everything worked fine. I just couldn't write my own module. The second part "Add Reference to Microsoft.Azure.Devices.Gateway DLL." did not work.

I just tried to install the package but no luck as well (package could not be found):


PM> Install-Package Microsoft.Azure.Devices.Gateway.Module
Install-Package : Das Paket "Microsoft.Azure.Devices.Gateway.Module" wurde nicht gefunden
In Zeile:1 Zeichen:1
+ Install-Package Microsoft.Azure.Devices.Gateway.Module
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Verstrichene Zeit: 00:00:00.9720067
PM> Install-Package Microsoft.Azure.Devices.Gateway.Win32
Install-Package : Das Paket "Microsoft.Azure.Devices.Gateway.Win32" wurde nicht gefunden
In Zeile:1 Zeichen:1
+ Install-Package Microsoft.Azure.Devices.Gateway.Win32
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Verstrichene Zeit: 00:00:00.4603353

Is it because of my VisualStudio 2015?
I also tried to set my project to 32Bit and changed .NET Core to 1.1.1 but no luck either.

Did I do something wrong? 

Best regards,
Zuendelmeister

**Comment by aribeironovaes** [comment]
Hi @zuendelmeister,

Yes, the latest version of .net core requires visual Studio 2017. It won't work with 2015.

If you meed to use lates version but can't install VS 2017 you can use .NET CORE CLI.

Let me know,

Cheers

Angelo Ribeiro

**Comment by Zuendelmeister** [comment]
Hi again,

now I'm jumping between two problems. When trying to add the project I get ether:
1.0.0-preview2-003131:
No executable found matching command "dotnet-add"
or
1.0.1:
The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Ideas?
Thanks as always.

**Comment by aribeironovaes** [comment]
Hi @Zuendelmeister, 

So, I was taking a look on how our samples are built and it may help you out. 
So, check the file: dotnet_core_managed_gateway.csproj....

You have the tag:     <TargetFramework>netcoreapp1.1</TargetFramework>

And Item Grou: 
For example: 
    <ProjectReference Include="..\dotnet_core_module_sample\modules\SensorModule\SensorModule.csproj" />

If you go to path: samples\dotnet_core_module_sample\modules\SensorModule\SensorModule.csproj
You will see that it has the TargetFramework, and ITemGroup Project Reference to the Microsoft.Azure.Devices.Gateway.csproj. 

So, here is my suggestion. 

Copy and paste SensorModule (changing it's name, class name and putting your code there), and edit the csproj to add your module. 

I know it's manual steps, but, if you are not using Visual Studio to add/remove project, this would be the path I would do.. I'm sure .NET Core CLI has a way of doing it, but we would have to check the .NET Core CLI Documentation for the best way of doing it. 

Can you try is out and let me know? 

Thanks, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @aribeironovaes,

what you suggest sounds good and I don't mind going through some manual steps.
Since I don't try to write a new module anymore and just to rewrite one of yours I was confident to succeed.
I tried to open the csproj file of my copied folder and got this error:
![image](https://cloud.githubusercontent.com/assets/14317353/25167500/ff578856-24df-11e7-840a-142061aeb503.png)

After that I got this:

![image](https://cloud.githubusercontent.com/assets/14317353/25167634/777c7cd8-24e0-11e7-9125-8bdc65b20b06.png)

So I added the mentioned line to the project element
`<Project Sdk="Microsoft.NET.Sdk"  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

And after clicking ok this:
![image](https://cloud.githubusercontent.com/assets/14317353/25167654/9674e166-24e0-11e7-9e6b-d9752bdfaa57.png)

Probably I just misunderstood something. Could you please tell me where I went wrong?

**Comment by aribeironovaes** [comment]
Hi @Zuendelmeister, 

I'm not sure, can you describe your steps? 
Are you opening the dotnet-core-biding.sln in a Visual Studio 2017? 
Do you have the latest version of .NEt Core? 1.1.1? 

Here is what I would do: 
1-Make sure you install the latest official version of .NET Core (1.1 from here: https://www.microsoft.com/net/core#windowsvs2017); 
2-Than open the file dotnet-core-binding.sln and build. 

On you build, you can to and start Editing the module (Sensor Module or Print module), adding your files and everything. 

I'm not understanding the message you pasted, but seems like problem on the version of the SensorModule Version and the version of .NET core you have. I've never seen the XML problem you pointed. 

Let me know, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @aribeironovaes,
no I use VS2015 as mentioned earlier. The solution does not work. Maybe because of my VS version?
![image](https://cloud.githubusercontent.com/assets/14317353/25215395/7011f410-259d-11e7-9efb-bdf0e9699a7b.png)

I edited the Printer- and SensorModule. Without my editing it looks like this:
![image](https://cloud.githubusercontent.com/assets/14317353/25215619/f44f7ddc-259e-11e7-936f-9a24bbac98b7.png)

Next week (maybe Tuesday) I will install VS2017. Let's wait until then. Maybe this solves all my problems. But shouldn't it work with VS2015 too?

Best regards,
Zuendelmeister

**Comment by aribeironovaes** [comment]
Hi Zuendelmeister,

Nops, the latest version of .NET Core just works with VS2017 or the CLI.

If you can change to 2017 it would be great, otherwise you would have to use the CLI or use an older version of .NET Core (but that would require to create all Modules for 2015.

Let us know if you can use 2017.

Thanks

Angelo Ribeiro

**Comment by Zuendelmeister** [comment]
Hi again @aribeironovaes,

thank you for your patience. I finally installed VS2017 and now everything just works.
Thanks for your help.

Best regards,
Zuendelmeister
