### ISSUE TITLE
TargetFrameworkVersion of Microsoft.Azure.Devices.Gateway package

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-gateway-sdk#203]
Hi team,

I'm using gwsdk .NET Core binding in part of my solution which is built as `netstandard1.4` based class libraries to enable unit testing on .NET Framework toolset.
However I cannot use the binding as is because the `Microsoft.Azure.Devices.Gateway`'s target framework version is currently `netstandard1.6` nevertheless it does not depend on any features require `netstandard 1.6`.

I cannot imagine other scenarios to justify change the .NET Standard version, but I think it is better to specify lower version if possible. Is it possible to change target framework lower such as `netstandard1.1`?

**Comment by aribeironovaes** [comment]
Hi Yusuke,

I don't know if we can go too low because of the version of the SDK. 

But my suggestion would be for you to try it out, change on the project and test it out. 

Let us know if it works and we can check on our side or you can submit a PR as well.

Thanks!

Angelo Ribeiro

**Comment by yfakariya** [comment]
Hi @aribeironovaes, thank you for quick response.
As far as my environment, I succeeded to change `<TargetFrameworkVersion>` to `netstandard1.1` and it looked fine (can be compiled and it just works). It is OK to make PR when I finish extra testing.

But I don't understand well about meaning of your "the version of the SDK". If it means `NetStandard.Library` package version, there are no problem to change to `netstandard1.1` because .NET Standard version (it just defines API compatibility set) is not related to .NET Core/SDK version (currently 1.0.4 and 1.1.1). 

I'm also not sure that you have plan to add APIs which only exist in `netstandard1.6` like `AssemblyLoadContext`. If so, changing to `netstandard1.x` is not acceptable.

**Comment by damonbarry** [comment]
We'll change our `<TargetFrameworkVersion>` to `netstandard1.3` (because we depend on the device SDK, and that's what it supports). We'll get this checked into `master` soon.

**Comment by yfakariya** [comment]
Thank you!

**Comment by damonbarry** [comment]
Fixed in the [latest](https://github.com/Azure/azure-iot-gateway-sdk/releases/tag/2017-04-27) release.
