### ISSUE TITLE
[.NET Binding][Suggestion] Add .NET Core support in .NET Binding

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-gateway-sdk#21]
(separated from #20)
It is great if .NET Binding also supports .NET Core (or add .NET Core binding) for C# (or other .net) code modules to run in linux.

Although coreclr itself does not support ARM linux, it is valuable to support .NET Core as well as UWP. I found that some hosting API does not exist in coreclr of non Windows builds, but I think it can be solved moving instantiation of managed objects from C++ to C# and uses static methods to communicate via `coreclr_create_delegate` API.

**Comment by tedvanderveen** [comment]
+1

**Comment by shz13009** [comment]
+1

**Comment by aribeironovaes** [comment]
Hey guys, I wonder if you saw that we now Support .NET Core Modules! :D It's in master already. 

So, do try and let us know. 

We have some known issues (like Windows x86), but we should be good on Windows x64 and Linux right now. (ARM is still not officially supported by .NET Core. 

Let us know. Cheers, 

Angelo Ribeiro.

**Comment by damonbarry** [comment]
.NET Core modules are supported in the [2017-03-06](https://github.com/Azure/azure-iot-gateway-sdk/tree/2017-03-06) release!

**Comment by yfakariya** [comment]
Thank you for great work! I'll try it.
