### ISSUE TITLE
[.NET Binding][Suggestion] Provide class based API instead of interface for .NET binding

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-iot-gateway-sdk#22]
(separated from #20)
For .NET binding, provide class based API instead of interface(`IGatewayModule`) like the Java binding. It has following problems:
- API usability. App developers must always implement all methods even if they want to only one method. `SensorModule` sample code is good example for it. Base class with nop virtual methods can solve this.
- API's backward compatibility. The interface is [not backward compatible](https://msdn.microsoft.com/en-us/library/ms229013%28v=vs.100%29.aspx).
- API design restriction. It prevents distinguish between internal APIs(SPIs) to communicate for native parts and public APIs to communicate to Apps. For example, internal APIs can expose `byte*` based APIs to avoid redundant copies of arrays.

**Comment by damonbarry** [comment]
>API usability. App developers must always implement all methods...

We're happy to take a contribution for a base class that implements the interface and provides default implementations.  :)

Overall, we don't see a compelling (enough) reason to replace the interface with a base class.
