### ISSUE TITLE
Development of azure-iot-gateway-sdk on Windows IoT 10 Core

### ISSUE THREAD

**Issue by nikirova** [Azure/azure-iot-gateway-sdk#228]
Hello,

I would like to inform me if and when you are planing to develop the azure-iot-gateway-sdk on windows iot 10 core and UWP platform
It's a very critical phase for us, as we have to decide if we'll stay in C#, UWP and windows iot 10 core, or we must change platform (we have already tested the sdk on ubuntu and java).

I would appreciate your answer,

Regards,
Niki

**Comment by damonbarry** [comment]
See #47 for more info; we'd like to support UWP and we believe it can be done using our existing APIs, but we don't have concrete plans to do the work anytime soon. We'd need a community contribution to make this happen.
