### ISSUE TITLE
CMake minimum version should respect flags

### ISSUE THREAD

**Issue by naveen26246** [Azure/azure-iot-gateway-sdk#235]
Hi, 

I am running into the issue below while tryinng to run **./build.sh --enable-nodejs-binding**. Any leads would be appreciated. 

-- Build files have been written to: /home/xxxx/azure-iot-gateway-sdk/build
Scanning dependencies of target parson
[  1%] Building C object core/deps/CMakeFiles/parson.dir/__/__/deps/parson/parson.c.o
Linking C static library libparson.a
[  1%] Built target parson
Scanning dependencies of target gateway
[  2%] Building C object core/CMakeFiles/gateway.dir/adapters/dynamic_library_linux.c.o
[  3%] Building C object core/CMakeFiles/gateway.dir/adapters/gb_library_linux.c.o
[  4%] Building C object core/CMakeFiles/gateway.dir/src/message.c.o
[  5%] Building C object core/CMakeFiles/gateway.dir/src/message_queue.c.o
[  6%] Building C object core/CMakeFiles/gateway.dir/src/module_loader.c.o
[  6%] Building C object core/CMakeFiles/gateway.dir/src/module_loaders/dynamic_loader.c.o
[  7%] Building C object core/CMakeFiles/gateway.dir/src/module_loaders/node_loader.c.o
[  8%] Building C object core/CMakeFiles/gateway.dir/__/proxy/message/src/control_message.c.o
[  9%] Building C object core/CMakeFiles/gateway.dir/__/proxy/outprocess/src/module_loaders/outprocess_loader.c.o
In file included from /home/xxxx/azure-iot-gateway-sdk/build_libuv/dist/include/uv.h:62:0,
                 from /home/xxxx/azure-iot-gateway-sdk/proxy/outprocess/src/module_loaders/outprocess_loader.c:8:
/home/xxxx/azure-iot-gateway-sdk/build_libuv/dist/include/uv-unix.h:66:30: fatal error: pthread-barrier.h: No such file or directory
 # include "pthread-barrier.h"
                              ^
compilation terminated.
make[2]: *** [core/CMakeFiles/gateway.dir/__/proxy/outprocess/src/module_loaders/outprocess_loader.c.o] Error 1
make[1]: *** [core/CMakeFiles/gateway.dir/all] Error 2
make: *** [all] Error 2

**Comment by zafields** [comment]
Which version of CMake do you have installed?

**Comment by naveen26246** [comment]
Updating the Cmake version has fixed the issue. Thanks @zafields.

**Comment by zafields** [comment]
@naveen26246 Thanks for finding this! We are going to have CMake check the minimum required version based on the flags passed.

**Comment by naveen26246** [comment]
@zafields ... sorry to bug you again.. but could you please look at https://github.com/Azure/azure-iot-gateway-sdk/issues/243. 
Its more like a query than an issue. I am not sure how to edit the content_type to any other type (default is uint8Array).

**Comment by zafields** [comment]
@naveen26246 I believe you MUST use that data type. I will make sure someone who knows for sure answers you on your thread.
Also, thanks for reporting the original bug from this post. I've updated the CMake to catch the versioning error. I'm going to close this issue, but you should be able to track #243 at #243 from now on.
