### ISSUE TITLE
broken link in out-of-process readme.

### ISSUE THREAD

**Issue by stevebus** [Azure/azure-iot-gateway-sdk#242]
Simple Doc bug...     

the hyperlink in this readme (https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/proxy_sample/README.md) to the "outprocess high level design" (second paragraph) is busted, returning a 404..

Pretty sure it should point here ->  https://github.com/Azure/azure-iot-gateway-sdk/blob/master/proxy/outprocess/devdoc/outprocess_hld.md

**Comment by zafields** [comment]
Thanks for pointing this out, we'll get it fixed!
