### ISSUE TITLE
Gateway compiling issue

### ISSUE THREAD

**Issue by girishlc** [Azure/azure-iot-gateway-sdk#248]
Hi,
I get the below error while Debug and/or Release build 

       "C:\cc\azure-iot-gateway-sdk\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "C:\cc\azure-iot-gateway-sdk\build\core\gateway.vcxproj.metaproj" (default target) (13) ->
       "C:\cc\azure-iot-gateway-sdk\build\core\gateway.vcxproj" (default target) (42) ->
       (Link target) ->
         LINK : fatal error LNK1181: cannot open input file '..\..\build_libuv\dist\lib\libuv.lib' [C:\cc\azure-iot-gateway-sdk\build\core\gateway.vcxproj]

       "C:\cc\azure-iot-gateway-sdk\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "C:\cc\azure-iot-gateway-sdk\build\proxy\modules\native_module_host\native_module_host.vcxproj.metaproj" (default target) (30) ->
       "C:\cc\azure-iot-gateway-sdk\build\proxy\modules\native_module_host\native_module_host.vcxproj" (default target) (46) ->
         LINK : fatal error LNK1181: cannot open input file '..\..\..\..\build_libuv\dist\lib\libuv.lib' [C:\cc\azure-iot-gateway-sdk\build\proxy\modules\native_module_host\native_module_host.vcxproj]

    45 Warning(s)
    2 Error(s)

Time Elapsed 00:00:11.79

C:\cc\azure-iot-gateway-sdk\tools>build.cmd --config Release --platform x64 --enable-java-binding

Tred with the Debug build, same issue

build.cmd --config Debug --platform x64 --enable-java-binding

**Comment by darobs** [comment]
Are you building with Visual Studio 2017?  Libuv is currently not building with VS2017.  There is a fix in a pull request, but it hasn't been merged (the last we checked).

Libuv is currently only being used with Node.js bindings and out of process modules, so if you don't need or want out of process modules, you may want to add "--disable-native-remote-modules" to the build command line.

**Comment by girishlc** [comment]
Hey Darobs,
Thanks for the input, I'm able to build successfully now 👍 
Earlier I tried to build in both VS 2015 and 2017, and I was getting error in both.

         umqtt.lib(mqtt_client.obj) : warning LNK4099: PDB 'umqtt.pdb' was not found with 'umqtt.lib(mqtt_client.obj)' or at 'C:\dd\azure-iot-gateway-sdk\build\modules\iothub\Debug\umqtt.pdb'; linking object as if no debug info [C:\dd\a
       zure-iot-gateway-sdk\build\modules\iothub\iothub.vcxproj]
         umqtt.lib(mqtt_codec.obj) : warning LNK4099: PDB 'umqtt.pdb' was not found with 'umqtt.lib(mqtt_codec.obj)' or at 'C:\dd\azure-iot-gateway-sdk\build\modules\iothub\Debug\umqtt.pdb'; linking object as if no debug info [C:\dd\azu
       re-iot-gateway-sdk\build\modules\iothub\iothub.vcxproj]
         umqtt.lib(mqtt_message.obj) : warning LNK4099: PDB 'umqtt.pdb' was not found with 'umqtt.lib(mqtt_message.obj)' or at 'C:\dd\azure-iot-gateway-sdk\build\modules\iothub\Debug\umqtt.pdb'; linking object as if no debug info [C:\dd
       \azure-iot-gateway-sdk\build\modules\iothub\iothub.vcxproj]

    57 Warning(s)
    0 Error(s)

Time Elapsed 00:00:22.36

C:\dd\azure-iot-gateway-sdk>tools\build.cmd --config Debug --platform x64 --enable-java-binding --disable-native-remote-modules

C:\dd\azure-iot-gateway-sdk>cd build\samples\java_sample

C:\dd\azure-iot-gateway-sdk\build\samples\java_sample>Debug\java_sample.exe ..\..\..\samples\java_sample\src\java_sample_win.json
gateway successfully created from JSON
gateway shall run until ENTER is pressed
Printer Module Received: Content: 40.161613237232984
Properties: {Source=27486089}
Printer Module Received: Content: 4.877969097025359
Properties: {Source=27486089}
Printer Module Received: Content: 43.808524687497766
Properties: {Source=27486089}
Printer Module Received: Content: 3.8562569919926015
