### ISSUE TITLE
IoTHubHTTP Logger Module not working

### ISSUE THREAD

**Issue by twgcriot** [Azure/azure-iot-gateway-sdk#28]
IoTHubHTTP Module can't connect to IoT Hub when running the TI Sensor sample:

**linaro@linaro-alip:~/Desktop/build/samples/ble_gateway_hl$ ./ble_gateway_hl** gateway_sample.json 
Gateway is running.
[2016:08:19T11:19:40] Model Number: N.A.
[2016:08:19T11:19:40] Serial Number: N.A.
[2016:08:19T11:19:40] Firmware Revision Number: 1.5 (Oct 23 2013)
[2016:08:19T11:19:41] Hardware Revision Number: N.A.
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:488 curl_easy_perform() failed: Out of memory

Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:490 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:1848 unable to HTTPAPIEX_SAS_ExecuteRequest
[2016:08:19T11:19:41] Software Revision Number: N.A.
[2016:08:19T11:19:41] Manufacturer: Texas Instruments
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:488 curl_easy_perform() failed: Out of memory

Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:490 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1573 unable to HTTPAPIEX_SAS_ExecuteRequest
[2016:08:19T11:19:41] Temperature: (0.000000, 0.000000)
Error: Time:Fri Aug 19 11:19:41 2016 File:/media/linaro/FREE/azure-iot-gateway-sdk/deps/azure-c-shared-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:488 curl_easy_perform() failed: Out of memory

**Comment by andrew-buckley** [comment]
Hi @twgcriot. This issue was fixed a few weeks ago in our develop branch but the fix has not yet been merged into the master branch. I will be merging this into the master branch shortly. 

Thanks!

**Comment by twgcriot** [comment]
Thanks Andrew. Keep up the good work as this is an awesome sample!

**Comment by andrew-buckley** [comment]
No problem, @twgcriot! This has now been checked in.
