### ISSUE TITLE
Java Sample JSON File Configuration Issue

### ISSUE THREAD

**Issue by twgcriot** [Azure/azure-iot-gateway-sdk#29]
Java Bindings and Java Modules build fine as per documentation.

However running the java_sample produces following error (**JSON config. file used attached**):
[java_sample.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/428331/java_sample.txt)

Error: Time:Sat Aug 20 13:20:59 2016 File:/azure-iot-gateway-sdk/bindings/java/src/java_module_host_manager.c Func:JavaModuleHostManager_Create Line:81 **JAVA_MODULE_HOST_CONFIG does not match the JAVA_MODULE_HOST_CONFIG known by this manager.**
Error: Time:Sat Aug 20 13:20:59 2016 File:/azure-iot-gateway-sdk/bindings/java/src/java_module_host.c Func:JavaModuleHost_Create Line:129 Failed to create a JAVA_MODULE_HOST_MANAGER_HANDLE.
Info: Module Count: -1.
Error: Time:Sat Aug 20 13:20:59 2016 File:/azure-iot-gateway-sdk/bindings/java/src/java_module_host_hl.c Func:JavaModuleHost_HL_Create Line:71 Unable to create Java Module.
Error: Time:Sat Aug

 20 13:20:59 2016 File:/azure-iot-gateway-sdk/core/src/gateway_ll.c Func:gateway_addmodule_internal Line:217 Module_Create failed.
Error: Time:Sat Aug 20 13:20:59 2016 File:/azure-iot-gateway-sdk/core/src/gateway_ll.c 
Func:Gateway_LL_Create Line:87 Gateway_LL_Create(): Unable to add module 'java_module_host'. The gateway will be destroyed.
Info: Module Count: 0.
Info: Destroying JVM

**Comment by andrew-buckley** [comment]
Hi @twgcriot, please ensure that the **full classpath** is present for both java modules. 

Some background, the JVM is only instantiated once regardless of the number of modules that will be loaded. For this reason, it needs the full classpath of any/all classes that will be used during it's lifetime when it first starts and it needs to have all configuration data present too. For this reason, we require that the configuration parameters that are relevant to the JVM are identical for all java modules. So you should include both .jar files in the classpath of both modules.

Hope this helps,
-Andrew

**Comment by twgcriot** [comment]
Thanks Andrew. That fixed it.
