### ISSUE TITLE
Build errors on Ubuntu Server 15.10

### ISSUE THREAD

**Issue by Injac** [Azure/azure-iot-gateway-sdk#3]
Trying to run (master branch clone on server) **build.sh** from the **tools** directory, results in the following error message:

`
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:77 (add_subdirectory):
  The source directory

    /home/ilija/source/azure-iot-gateway-sdk/deps/azure-c-shared-utility

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:80 (add_subdirectory):
  add_subdirectory given source "./deps/azure-iot-sdks/c" which is not an
  existing directory.

CMake Error at core/tests/gwmessage_unittests/CMakeLists.txt:22 (build_test_artifacts):
  Unknown CMake command "build_test_artifacts".

-- Configuring incomplete, errors occurred!
See also "/home/ilija/source/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
`

Looks like there are files missing. 

UPDATE: Forgot the --recursive flag.

**Comment by WilliamBerryiii** [comment]
Leaving a note that the `--recursive` parameter is for the git checkout. 
i.e. `git clone --recursive https://github.com/Azure/azure-iot-gateway-sdk.git`
