### ISSUE TITLE
[.NET Binding] Suggest to import "dotnet_hl.dll" in NativeDotNetHostWrapper instead of "dotnet.dll"

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-gateway-sdk#31]
In "Microsoft.Azure.IoT.Gateway" project, "NativeDotNetHostWrapper" class imports "dotnet.dll" to get C function pointer of "Module_DotNetHost_PublishMessage".
Modules use .NET binding has pre-requirement to load "dotnet_hl.dll" in gateway executable. 
As "Microsoft.Azure.IoT.Gateway" project reference is essential for modules developed using .NET, the gateway executable will need to load both "dotnet_hl.dll" and "dotnet.dll".
Since "dotnet_hl.dll" is a superset of "dotnet.dll", loading both "dotnet_hl.dll" and "dotnet.dll" is redundant to gateway executable.
Suggest to import "dotnet_hl.dll" in "Microsoft.Azure.IoT.Gateway".
By doing so, users won't have to copy "dotnet.dll" to working directory, this could also eliminate the runtime errors for those who doesn't know "dotnet.dll" is one of the dependency for "Microsoft.Azure.IoT.Gateway".

**Comment by aribeironovaes** [comment]
Hi @yphuangms , 

We have solve this problem, we have removed the _hl.dll and now it's just 1 DLL. 
So, I'm closing this issue. Please check it out and reactivate the issue if you have any more request about this. 
Thanks a lot for using our Azure IoT Gateway SDK!

Angelo Ribeiro.
