### ISSUE TITLE
Problem building the sample

### ISSUE THREAD

**Issue by BenjaminMellon** [Azure/azure-iot-gateway-sdk#33]
Hello,
I have a problem while building the sample, i run the build.cmd with a developer command prompt and i have those errors :
![cmake build error](https://cloud.githubusercontent.com/assets/22390147/18779169/1c33b000-8178-11e6-8a39-753576b71dbc.JPG)

Do you have solutions ?

**Comment by darobs** [comment]
Hi @BenjaminMellon, thank you for looking at our project!

Usually, those type of errors are due to the submodules not being populated.  Please try this in the repository:
```
git submodule update --init --recursive
```

I hope that helps.  Please let me know if you still run into problems.

**Comment by BenjaminMellon** [comment]
Hello @darobs and thanks for your answer,
I tried the command line, but had this error
![git error](https://cloud.githubusercontent.com/assets/22390147/18829527/f7a555ce-83dc-11e6-9066-50be4097ff7b.jpg)
So i tried to install git, i created a git repository, i added, commited and pushed the files but nothing changed. Always the same error. I think I'm missing something....

**Comment by aribeironovaes** [comment]
Hi @BenjaminMellon, 

The first error is because you have to be on the same folder you have cloned our repo in order to run the command mentioned by @darobs. 

Let us know, 

Angelo Ribeiro.

**Comment by BenjaminMellon** [comment]
Hi @aribeironovaes and thank you for your answer,
I ran the build into the cloned repo and had this
![giterror3](https://cloud.githubusercontent.com/assets/22390147/18905112/d66cb754-8561-11e6-9dea-7dddcb335a87.JPG)

**Comment by andrew-buckley** [comment]
Hi @BenjaminMellon,

Just to clarify, did you follow the Setup and Building instructions outlined [here](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/doc/getting_started.md)? 

When you clone the repo, you should either clone it recursively, or after cloning it, _cd_ into the root of the cloned repository and run the command @darobs described above. Then you should be able to either use the build command script or run cmake directly also described in the above document.

It seems like you ran the _git submodule update --init --recursive_ from the root of your machine, while you want to actually run it from the root of your git repository (the root of the azure-iot-gateway-sdk repository).

Hope this helps.

**Comment by BenjaminMellon** [comment]
Hi @andrew-buckley ,
Thank you for solving my problem ! I didn't see the `git clone --recursive https://github.com/Azure/azure-iot-gateway-sdk.git` , just ran it and it works great.
Thank you all for the help.

**Comment by darobs** [comment]
HI @BenjaminMellon, I'm glad @andrew-buckley solved your issue.  I'm going to close this Issue.
