### ISSUE TITLE
Problems building dotnet_binding_sample

### ISSUE THREAD

**Issue by leeprtc** [Azure/azure-iot-gateway-sdk#38]
I'm seeing errors when building dotnet_binding_sample under AzureIoTGateway_Samples. There seems to be some issues with the cmake configuration file. The binary compiled without issues. But the build is failing because it has trouble copying SensorModule and PrinterModule binaries. These are .NET assemblies but it seems to be detected by cmake as C/C++ projects as I see something like the following in the logs.

  "C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different C:/GitHub/azure-iot-gateway-sdk/build/../bindings/dotnet/dotnet-binding/SensorModule/bin/x86/Debug/SensorModule.dll ....
  ...
 "C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different C:/GitHub/azure-iot-gateway-sdk/build/../bindings/dotnet/dotnet-binding/PrinterModule/bin/x86/Debug/PrinterModule.dll ....

Is this a known issue?

Also, I'm just curious, is there a reason why the projects in azure-iot-gateway-sdk\bindings\dotnet\dotnet-binding are not added to azure_iot_gateway_sdk solution when you run build.cmd with --enable-dotnet-binding? Since dotnet_binding_sample project has a dependency on some of the projects in azure-iot-gateway-sdk\bindings\dotnet\dotnet-binding, it seems logical to be able to find these projects in azure_iot_gateway_sdk solution.

Thanks,

Peter.

**Comment by aribeironovaes** [comment]
Hi @leeprtc 

So, before run the build.cmd with --enable_dotnet_binding, please, make sure you run the script build_dotnet.cmd. We created this script so you don't need to copy manually the DLLs for the DotNet Sample to work. 

Regarding your second question it's a good suggestion, however do you know if it's possible to accomplish this with CMake? The azure_iot_gateway_sdk solution is generated by CMAKE and if you know a good way of accomplish that let us know. 

Thanks, 

Angelo Ribeiro.

**Comment by leeprtc** [comment]
Thanks for the info about build_dotnet.cmd. I was not aware that I needed to run this first before build.cmd.

Unfortunately, I'm not that familiar with CMake since I do most of my development with Visual Studio. I suppose one can use Visual Studio extensibility to patch up the solution after CMake runs. But it may not be worth the trouble to create/maintain this separate program if there is documentation about this.

Peter.

**Comment by darobs** [comment]
Hello @leeprtc we have just updated the documentation for the dotnet sample to make it more clear the steps needed to build the .NET sample.

> At this point, gateways containing .NET modules are only supported on Windows 
Desktop.
 The sample Gateway gets built when you build the SDK by first running
``` 
tools\build_dotnet.cmd
```
then running 
```
tools\build.cmd --enable-dotnet-binding
```

We are closing this issue, if you don't think the issue has been resolved, please reopen this or create a new issue.  

Thanks, 
Dave
