### ISSUE TITLE
azure-iot-gateway-sdk for ARM based Board

### ISSUE THREAD

**Issue by SurinderGanotra** [Azure/azure-iot-gateway-sdk#4]
We have downloaded and build the azure-iot-gateway-sdk for win32 platform on windows 10 as per the instructions provided in the devbox_setup.md and getting_started.md. But we are not able to build the gateway sdk for ARM platform for Raspberry Pi 3 board.
Could you please help me to build the gateway for ARM platform in windows.

**Comment by avranju** [comment]
Just to confirm, are you trying to build this for Windows 10 IoT Core?

**Comment by SurinderGanotra** [comment]
Yes, we are trying to build it for windows 10 IOT Core, but for ARM based
board Rasbperry PI 3.

**Comment by SurinderGanotra** [comment]
After some struggle, I have found the way to build the Microsoft Gateway SDK for ARM processor using Visual Studio, below are the steps to build the SDK for ARM configuration
1.	Go to Configuration Manager in Visual Studio and create new configuration ARM based on Win32.
2.	Go to All Options of Linker\Librarian under the properties of each project and remove the Additional Options( /machine:X86 %(AdditionalOptions)). Follow this for each project you need to build for ARM configuration.

**Comment by avranju** [comment]
Thanks for the update @SurinderGanotra. We'll add this to the backlog anyway and see if this process can be made simpler.
