### ISSUE TITLE
IoT Gateway and device management

### ISSUE THREAD

**Issue by ondrejtomcik** [Azure/azure-iot-gateway-sdk#41]
Azure now supports in device management preview for IoT Hub configuration of tags -> location hierarchies and others. I read that 'We’ve also integrated standards like LWM2M for device management'.
What exactly does it mean please?

Is it possible to get/set device management metadata (tags) directly from gateway locally, when connection is down? Is this information stored also there?

Thanks.

**Comment by damonbarry** [comment]
Your questions about device management should be directed to the repo at https://github.com/Azure/azure-iot-sdks-preview.

RE setting/getting device management metadata while the gateway is offline: The gateway is also in beta, and we don't have built-in support yet for device management in the gateway. We plan to add support soon after device management becomes generally available, but it's difficult right now to say how it will look.
