### ISSUE TITLE
What happened to UWP samples?

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-iot-gateway-sdk#46]
Both code and documentation?
They seem to disappeared.

**Comment by aribeironovaes** [comment]
Hi @alexiordan, 

Thanks for asking. We decided to remove the UWP Sample from our code temporarily since it didn't follow our guideline on binding. We want to avoid #defines in our code and UWP had that. 

We are making some changes to our core architecture so it's more amenable to environments like UWP.

Thanks, 

Angelo Ribeiro.

**Comment by alexiordan** [comment]
Should usage mode be expected to change?

**Comment by aribeironovaes** [comment]
@alexiordan, 

Thanks for the feedback. 

When we release to master we add a "Breaking Change" section so users are aware before switching versions.

So, what usage mode are you asking? On the last release (we made yesterday) we had some breaking changes, specially regarding Modules Loading. We have updated our samples and documentation with these changes. But let us know if you have any questions. 

I would say that yes, if you need UWP use previous version and let us know that you are waiting to use UWP with a newer version of the gateway so we can prioritize our backlog accordingly. 

Thanks a lot, 

Angelo Ribeiro.

**Comment by alexiordan** [comment]
I plan to use the Gateway so to integrate some ZigBee modules into Azure IoT Hub world. I will run the Gateway as an UWP background app on Windows 10 Core on a Raspberry Pi 3.

Currently, iothub, logger and identity map (maybe I need to rewrite this to accommodate ZigBee addressing) seems what I need.
I only need to write the module that sends/receives data to the ZigBee network.

From what I've read and tested, I think will work.  What do you think?
This is why I am looking forward to the uwp binding of those modules.

**Comment by aribeironovaes** [comment]
Thanks for letting us know @alexiordan. 
It's important for us to understand your scenario. 

Yeah, the way that UWP was written a native module (existing Iothub, logger, identity map) would not work on the UWP Gateway. The user (or us) would have to wrap existing modules or rewrite equivalent modules in UWP. It's one of the reason we decided to go with a new approach that would allow us to reuse more code without duplicating code for UWP. 

So, to answer your question you could totally make a uwp gateway (using previous version, not the latest one) and write your modules for UWP. 

Once we have a better UWP binding we will make sure you know. It's on our backlog.

Thanks again, 

Angelo Ribeiro.

**Comment by alexiordan** [comment]
Thank you @aribeironovaes.
I'll then further use the previous version whilst waiting for the UWP release.
