### ISSUE TITLE
Edge Analytics in azure-iot-gateway-sdk

### ISSUE THREAD

**Issue by SurinderGanotra** [Azure/azure-iot-gateway-sdk#5]
Hi, 
I was trying to find out the modules for Edge Analytic's in the azure-iot-gateway-sdk, but not able to find out in the SDK Gateway. Does it available in the Gateway SDK or we need to develop custom modules for edge analytics.

**Comment by chipalost** [comment]
Hi Surinder, we do not have an edge analytics module available at the moment but providing one is a top priority for us. I’d love to find out more about your scenario. Please email me at cstreet@microsoft.com.
