### ISSUE TITLE
BLEIO_gatt_read_char_by_uuid Line:155 g_tree_lookup() failed.

### ISSUE THREAD

**Issue by yaweiw** [Azure/azure-iot-gateway-sdk#51]
```
Error: Time:Mon Nov 14 03:37:05 2016 File:/media/Storage/SourceCode/WindRiver/Projects/iot-cloud/build-intel-baytrail-64-0013/bitbake_build/tmp/work/corei7-64-wrs-linux/azure-iot-gateway-sdk/2016-09-01-r4/git/modules/ble/src/ble_gatt_io_linux_read.c Func:BLEIO_gatt_read_char_by_uuid Line:155 g_tree_lookup() failed.
```

We are facing this issue intermittently on Intel NUC running Wind river.

**Comment by darobs** [comment]
@yaweiw Are you still experiencing this problem?  I know we had a bug in the BLE module a few weeks ago, and these fixes have been merged into the latest master commit.  My first suggestion is to get the latest form master (or develop) and see if this problem is resolved.

**Comment by yaweiw** [comment]
@darobs yes i am still facing the issue. but running bluetoothctl list-attributes before the sample works. so this should server as a workaround though.

**Comment by darobs** [comment]
That is the workaround.  The current BLE module doesn't do attribute discovery on its own, and we instruct the user to connect via bluetoothctl in our [setup document](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/ble_gateway/connecting_to_ble_device_on_rpi3.md).

We are closing this issue, if you don't think the issue has been resolved, please reopen this or create a new issue. 
Thanks, 
Dave
