### ISSUE TITLE
[Suggestion][Dotnet-Binding] Allow to take JSON for "args" rather than just a string.

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-gateway-sdk#56]
While looking at native modules, it allow to take JSON object definitions as "args", but this is currently not available for dotnet modules. 

        {
            "name": "logger",
            "loader": {
                "name": "native",
                "entrypoint": {
                    "module.path": "..\\..\\..\\modules\\logger\\Debug\\logger.dll"
                }
            },
            "args": {
                "filename": "log.txt"
            }
        }

Dotnet modules takes string for "args", not JSON object definitions as above.

       {
            "name": "dotnet_sensor_module",
            "loader": {
                "name": "dotnet",
                "entrypoint": {
                    "assembly.name": "SensorModule",
                    "entry.type": "SensorModule.DotNetSensorModule"
                }
            },
            "args": "module configuration"
        }

Current workaround is to use a lot of "\"" inside string to carry JSON definition within a string as arguments for dotnet module. Suggest to allow dotnet loader to take JSON and then by serializing JSON definitions to string before passing to dotnet module.

**Comment by aribeironovaes** [comment]
Thanks @yphuangms, 

I have added your suggestion to our backlog for triage/consideration. 

Question for you. If you add a JSON like this: 
   {
        "name": "dotnet_sensor_module",
        "loader": {
            "name": "dotnet",
            "entrypoint": {
                "assembly.name": "SensorModule",
                "entry.type": "SensorModule.DotNetSensorModule"
            }
        },
        "args": "{"filename": "log.txt" }"
    }

Wouldn't you be able to parse your JSON on your DotNEt Module? (I didn't test that btw). 

Leaving it as is (a string) has it's advantage for modules that want configuration to be in another format other than JSON.. 

Thanks, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Hi @yphuangms , 

Actually I'm going to take back what I said. 
I just edited the dotnet_binding_sample JSON to something like this: 
        {
            "name": "dotnet_sensor_module",
            "loader": {
                "name": "dotnet",
                "entrypoint": {
                    "assembly.name": "SensorModule",
                    "entry.type": "SensorModule.DotNetSensorModule"
                }
            },
            "args": {
                "filename": "log.txt"
            }
        },

So, I was able to receive the JSON as my configuration like this: "{\"filename\":\"log.txt\"}"

So, Can you clarify your request? 

Let me know, 

Angelo Ribeiro.

**Comment by damonbarry** [comment]
As @aribeironovaes said above, we believe this issue is already fixed in our latest release ([2016-11-18](https://github.com/Azure/azure-iot-gateway-sdk/tree/2016-11-18)). Please reopen if you still see this in the latest bits.
