### ISSUE TITLE
[.Net Binding]: Regression: Module args are quoted and escaped

### ISSUE THREAD

**Issue by barnstee** [Azure/azure-iot-gateway-sdk#59]
In the GA bits, there is a regression when it comes to the args strings that is passed to modules: The string is now quoted with double-quotes and appears to be escaped. In the OPC.UA module, the args are used for device ID and shared access key, which now no longer works:
Device Id had quote sign at start and shared key had it at the end, as 606simps noted. I fixed that in my local code, but did not work anyway. Because it was adding back slash ( \ )before forward slash ( / ) in the shared key. Something to do with encoding or reading of config file.

**Comment by aribeironovaes** [comment]
Working on that now @barnstee . 

I will let you know.

**Comment by aribeironovaes** [comment]
Hi @barnstee, 

Thanks for raising this. So, here is what we came: 
So, I tested and you are right, for a .NET module develop the latest change we make can cause a regression. 

Although we think that the current implementation is better than the previous one for the following reason:
Before the configuration just accepted pure String Configuration (like the one you are using on OPC US MODULE “devicekey;somethingelse”. Now the user can actually put JSON value (include pure strings). 

So, just to summarize: 

Before we used to have: 
            "args": {
                "dotnet_module_args": "module configuration"
            }

And the DotNEt Module received: module configuration as it’s content.

Now we are proposing having things like this: 
            "args": "module configuration"
Or 
            "args": {
                    "arg1": "value1",
                    "arg2": "value2"
                    }

And you would receive on your DotNEt Module: 
\”module configuration\”
Or
{\"arg1\":\"value1\",\"arg2\":\"value2\"}


And we now can claim that we support all types of JSON (Which we couldn’t do before). 
Example this: 
[
                {
                    "firstName": "John",
                    "lastName": "Doe"
                },
                {
                    "firstName": "Anna",
                    "lastName": "Smith"
                },
                {
                    "firstName": "Peter",
                    "lastName": "Jones"
                }
            ]
Would turn into this on our .NET Module
[{\"firstName\":\"John\",\"lastName\":\"Doe\"},{\"firstName\":\"Anna\",\"lastName\":\"Smith\"},{\"firstName\":\"Peter\",\"lastName\":\"Jones\"}]

This one the only thing you should do on your module would be to parse whatever you receive as JSON. 


So, with that, I will go ahead and close the issue. 

Thanks a lot Erich!

Angelo Ribeiro.
