### ISSUE TITLE
Errors while running CTest

### ISSUE THREAD

**Issue by SKVasanth** [Azure/azure-iot-gateway-sdk#6]
Team,

FYI, Below Tests are failed while running SDK in ubuntu 16.04 LTS VM. 

96% tests passed, 4 tests failed out of 102

Total Test time (real) =   2.81 sec

The following tests FAILED:
	 61 - iothubclient_http_e2etests (Failed)
	 63 - iothubclient_mqtt_e2etests (Failed)
	 65 - iothubclient_amqp_e2etests (Failed)
	 91 - gw_e2etests (Failed)
Errors while running CTest

61/102 Test  #61: iothubclient_http_e2etests .............***Failed    0.06 sec
Error: Time:Mon May 23 23:07:55 2016 File:/home/vasanth/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:434 Failure retrieving Connection Strings values.
 === Executing test suite iothubclient_http_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

 63/102 Test  #63: iothubclient_mqtt_e2etests .............***Failed    0.06 sec
Error: Time:Mon May 23 23:07:55 2016 File:/home/vasanth/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:434 Failure retrieving Connection Strings values.
 === Executing test suite iothubclient_mqtt_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

65/102 Test  #65: iothubclient_amqp_e2etests .............***Failed    0.02 sec
Error: Time:Mon May 23 23:07:55 2016 File:/home/vasanth/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:434 Failure retrieving Connection Strings values.
 === Executing test suite iothubclient_amqp_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

91/102 Test  #91: gw_e2etests ............................***Failed    0.03 sec
Error: Time:Mon May 23 23:07:55 2016 File:/home/vasanth/azure-iot-gateway-sdk/deps/azure-iot-sdks/c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init Line:434 Failure retrieving Connection Strings values.
 === Executing test suite gw_e2etests ===
  Assert failed: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

And it doesn't stop me the execution of samples, executed Hello_world sample.

**Comment by andrew-buckley** [comment]
Hi @SKVasanth, it looks like you're trying to run our end to end tests. In order to do this you will have to set a couple of environment variables. You will need to have a valid IotHub and set the environment variables "IOTHUB_CONNECTION_STRING" and "IOTHUB_EVENTHUB_CONNECTION_STRING" to valid IotHub and EventHub connection strings. Once you do this you will be able to run the end to end tests. Do note that running the end to end tests is optional.
