### ISSUE TITLE
[.Net binding] How to enable .Net binding needs to be more discoverable in the docs

### ISSUE THREAD

**Issue by barnstee** [Azure/azure-iot-gateway-sdk#60]
Lots of folks forget to run tools\build_dotnet.cmd and tools\build.cmd --enable-dotnet-binding because the only place it's mentioned is n the .Net binding sample. If you just clone the SDK and a .Net module and want to get it working, it is almost impossible to find this.

**Comment by andrew-buckley** [comment]
Hi @barnstee would it be helpful to provide links to the setup instructions on the main README.md page?

**Comment by barnstee** [comment]
Yes.

**Comment by barnstee** [comment]
And possible have a build dev doc here: https://github.com/Azure/azure-iot-gateway-sdk/tree/master/bindings/dotnet/devdoc

**Comment by andrew-buckley** [comment]
@barnstee, here is a commit I've made to make the binding instructions more find-able. Does this seem good to you? 

https://github.com/andrew-buckley/azure-iot-gateway-sdk/commit/02918f9b34d890f3f90e57ee93fb0d72a23efb27

**Comment by barnstee** [comment]
Looks good! Thank you!
