### ISSUE TITLE
Simulated IoT Gateway SDK Sample Project Errors: Failed to open the connection with CBS and AMQP transport failed to establish connection with the service, respectively.

### ISSUE THREAD

**Issue by kingsolutions** [Azure/azure-iot-gateway-sdk#68]
I have successfully build the azure-iot-gateway-sdk repository. However, I have some issues in run the solution as stated above.

Please find screen shots here:
![image](https://cloud.githubusercontent.com/assets/11579962/21075730/03c0784e-bee7-11e6-8dd6-4ba339facdda.png)

I have tried all I could to fix these errors, but to no success. Could somebody help, please?

Thanks in advance

Kingsley

**Comment by damonbarry** [comment]
The error at the top of the stack (first line in the output above) shows that getaddrinfo fails with 11001, which is "host not found". Things I can think of that would cause that are:
 - wrong IoTHubName and/or IoTHubSuffix in the JSON config file
 - no connection to the internet
 - an outage somewhere between your device and the service

Are you still seeing this problem?

**Comment by kingsolutions** [comment]
Yes, I'm still having the errors.

Please can you have a look at my json configuration file and see what I'm doing wrong:
===============================================================
{
  "modules": [
    {
      "name": "IotHub",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\iothub\\Debug\\iothub.dll"
        }
      },
      "args": {
        "IoTHubName": "Myhub-Hub.azure-devices.net",
        "IoTHubSuffix": "azure-devices.net",
        "Transport": "AMQP"
      }
    },
    {
      "name": "mapping",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\identitymap\\Debug\\identity_map.dll"
        }
      },
      "args": [
        {
          "macAddress": "01:01:01:01:01:01",
          "deviceId": "WHART-IP1",
          "deviceKey": "tVDmumT5etcbnmutecstttcc99999999"
        },
        {
          "macAddress": "02:02:02:02:02:02",
          "deviceId": "<<WHART-IP2>>",
          "deviceKey": "r9miDw1+55we327777777fh77777fh770"
        }
      ]
    },
    {
      "name": "BLE1",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\simulated_device\\Debug\\simulated_device.dll"
        }
      },
      "args": {
        "macAddress": "01:01:01:01:01:01"
      }
    },
    {
      "name": "BLE2",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\simulated_device\\Debug\\simulated_device.dll"
        }
      },
      "args": {
        "macAddress": "02:02:02:02:02:02"
      }
    },
    {
      "name": "Logger",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "..\\..\\..\\modules\\logger\\Debug\\logger.dll"
        }
      },
      "args": {
        "filename": "deviceCloudUploadGatewaylog.log"
      }
    }
  ],
  "links": [
    {
      "source": "*",
      "sink": "Logger"
    },
    {
      "source": "BLE1",
      "sink": "mapping"
    },
    {
      "source": "BLE2",
      "sink": "mapping"
    },
    {
      "source": "mapping",
      "sink": "IotHub"
    }
  ]
}
=============================================================

Do I supposed to enter my IoT Hub  ConnectionString value instead of the IoTHubname value?

The module-path values are left as defaults since my cloned repository path is C:\azure-iot-gateway-sdk

This is the path of my cloned repository:
C:\azure-iot-gateway-sdk

I successfully built the repository by using C:\azure-iot-gateway-sdk\tools\build.cmd

To run the solution, I entered the following command on the VS2015 Command Tool:

C:\azure-iot-gateway-sdk\build\samples\simulated_device_cloud_upload\Debug\simulated_device_cloud_upload_sample.exe C:\azure-iot-gateway-sdk\samples\simulated_device_cloud_upload\src\simulated_device_cloud_upload_win.json

I'm I doing anything wrong here?

Thanks for your concern and help.

**Comment by kingsolutions** [comment]
Sorry, I have internet connection and my devices are all created  and enabled.

See screen shots here:

![image](https://cloud.githubusercontent.com/assets/11579962/21078612/82921aa4-bf43-11e6-9ffe-a4c29907e78a.png)

**Comment by damonbarry** [comment]
It looks like you specified your IoTHubSuffix value in both IoTHubName and IoTHubSuffix. IoTHubName should just be "Myhub-Hub".

**Comment by kingsolutions** [comment]
I have edited the IoTHubName value, this is the new error am getting: 

![image](https://cloud.githubusercontent.com/assets/11579962/21078683/2bbd6244-bf46-11e6-861b-99f8019c0adb.png)

**Comment by damonbarry** [comment]
I suspect your config file has this: `"deviceId": "<<WHART-IP2>>"`.
You should change it to: `"deviceId": "WHART-IP2"` (remove the angle brackets).
It looks like you configured `WHART-IP1` correctly.

**Comment by kingsolutions** [comment]
Thanks so much, Damonbarry. The solution ran successfully after following your observations, with no errors. 

Please do you know where I could find detailed documentation of the sample Simulated Device Cloud Upload solution?

Again, thanks for you help. I apprecite

**Comment by damonbarry** [comment]
The readme file in the sample directory has detailed information.
https://github.com/Azure/azure-iot-gateway-sdk/tree/master/samples/simulated_device_cloud_upload

Thanks!
Damon
