### ISSUE TITLE
Edison build fails during config due to host linker being invoked instead of cross linker

### ISSUE THREAD

**Issue by challinan** [Azure/azure-iot-gateway-sdk#71]
Using the Intel Edison toolchain and build corresponding script in "tools" subdirectory fails with 
**cannot find crt1.o: No such file or directory**
On analysis, during the CMake config steps where it tries to validate the C compiler, it correctly uses the Edison cross-compiler, but then the link step uses the host's linker (/usr/bin/ld)

That is obviously not correct behavior, and leads to the above error early in the build.

Adding this "hack" to the inteledision_c.sh script works around the problem:
**-DCMAKE_LINKER=/opt/poky-edison/1.7.2/sysroots/core2-32-poky-linux/usr/bin/i586-poky-linux-ld**

But CMake should behave when CMAKE_C_COMPILER and CMAKE_CXX_COMPILER are properly set to point to the compilers, which they are.  

I have verified this behavior on a clean clone, and made sure all the cmake cache files were deleted, etc.

Anyone know the "right" way to fix this?

**Comment by darobs** [comment]
Hello @challinan,  I'm looking at this issue, among other cross-compile issues.  I'm hoping to get back to you soon.

**Comment by damonbarry** [comment]
[899eb5b](899eb5bdd334234b7e8e882159392585c0aa9a36)

**Comment by damonbarry** [comment]
Fix is in master
