### ISSUE TITLE
Simulating a WirelessHART -Enabled Gateway SDK

### ISSUE THREAD

**Issue by kingsolutions** [Azure/azure-iot-gateway-sdk#74]
Hello,
I know the MS Azure IoT Gateway SDK contains the infrastructure and modules to create IoT gateway solutions.
How do we modify or customize the current Real Device sample IoT Gateway solution that is based on Raspberry hardware and Bluetooth Low Power device to a Windows machine(hardware) and any low power device category?
Thanks in advance
Kingsley

Kingsley

**Comment by avranju** [comment]
The Gateway SDK itself will run fine on a Windows device. As for device connectivity you may need to write a module for the specific device that you wish to connect to. Modules can be written in C, Java, C# (or any other .NET language) or JavaScript (Node.js).

**Comment by kingsolutions** [comment]
Thanks so much Avranju.
Please do you know the path to the source file of the relevant sample module?

**Comment by avranju** [comment]
If you're writing your module in C then the simplest example to look at would be in `modules/hello_world`. For a .NET module `bindings/dotnet/dotnet-binding/PrinterModule` is a simple example. For Java take a look at `samples/java_sample/java_modules/Printer` and finally for Node.js `samples/nodejs_simple_sample/nodejs_modules/printer.js` is a good starting point.

**Comment by kingsolutions** [comment]
Thanks again. I got it!
