### ISSUE TITLE
Projects build without symbols

### ISSUE THREAD

**Issue by meesern** [Azure/azure-iot-gateway-sdk#77]
Hi - I find that having run cmake I can use Visual Studio (2015) to rebuild the projects (specifically simulated_device_cloud_upload_sample).  I get the executable but cannot debug because there are no associated .pdb files for any of the source.  Debugger returns:

'simulated_device_cloud_upload_sample.exe' (Win32): Loaded '...azure-iot-gateway-sdk\samples\simulated_device_cloud_upload\Debug\simulated_device_cloud_upload_sample.exe'. Module was built without symbols.

I have not been able to find how to 'switch on' symbol generation.
It would seem better to have symbol generation on by default in all projects.

**Comment by avranju** [comment]
Are you building a [debug](https://msdn.microsoft.com/en-us/library/wx0123s5.aspx) build in VS? That should generate symbols and you should be able to debug into the source.

**Comment by meesern** [comment]
Thanks @avranju  Yes - I'm using the "Debug" solution configuration and the "Win32" solution platform in VS15.  I have tried clean builds.  I agree it should generate symbols but does not.  In VS15 I cannot find a flag or option to enable/disable symbol generation.  The documents seem to say that it will always build symbols.  Might cmake be setting some kind of option in some configuration file?

**Comment by avranju** [comment]
**CMake** doesn't specify the build configuration for Visual Studio (unlike for instance a *makefile* build where we can cause it to generate a debug version of the makefile). It's weird that it's not generating PDBs for you even in the debug configuration. In fact, by default, VS should generate PDBs even in the release build configuration.

I suppose you could try fiddling with the debug build settings as documented [here](https://msdn.microsoft.com/en-us/library/xe4t6fc1.aspx) and see if that helps.

**Comment by meesern** [comment]
I have now found an option in VS15  under the project properties:

Properties->Configuration Properties->Linker->Debugging->Generate Debug Info

This was blank and needs to be set to "Optimize for Debugging (/DEBUG)".  Following this a 'Clean' is necessary to recompile the code with symbols.

**Comment by damonbarry** [comment]
Closing, since you've found a solution.

I'll also note that, with the latest bits from `develop`, I used `tools\build.cmd` to do cmake build, then opened `build\azure_iot_gateway_sdk.sln` in VS2015 and rebuilt the project `simulated_device_cloud_upload_sample`. After I set that project as the startup project in VS and hit F10, it stepped into the main function without a hitch.
