### ISSUE TITLE
Slow clone of node repo

### ISSUE THREAD

**Issue by Kordonme** [Azure/azure-iot-gateway-sdk#78]
It takes an awful lot of time to clone the node repo and checkout that branch. Isn't it possible to use `--depth 1` to save some time?

`git clone -b shared-691 https://github.com/avranju/node.git --depth 1`

**Comment by avranju** [comment]
Makes sense. Yes, we can certainly do that. Will get this done.

**Comment by avranju** [comment]
This change has now been checked-in to the *develop* branch - https://github.com/Azure/azure-iot-gateway-sdk/commit/08f073f0874ee1845dfd08269dddc3483a18bad9.
