### ISSUE TITLE
Building for Raspberry Pi 3 on Raspbian - '__x86_64__ exist failed'

### ISSUE THREAD

**Issue by bironology** [Azure/azure-iot-gateway-sdk#79]
Hello,

I was following along with the https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-gateway-sdk-physical-device tutorial. Well, after what seemed like over an hour (I had dinner), it errored out. 

I'm unfamiliar with this codebase, but the errors seem like pretty basic stuff.

Determining if the __x86_64__ exist failed with the following output:...
...
Determining if the __i386__ exist failed with the following output:

This is a Pi 3 Model B running Raspbian Jessie. Details specs follow, and contents of CMakeError.log and CMakeOutput.log attached.

[CMakeOutput.log.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/670720/CMakeOutput.log.txt)
[CMakeError.log.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/670721/CMakeError.log.txt)

------------------
Raspberry Pi 3 Model B Motherboard
1.2GHz 64-bit quad-core ARMv8 CPU, 1 GB RAM
802.11n Wireless LAN, 10/100Mbps Lan Speed
Bluetooth 4.1, Bluetooth Low Energy
4 USB ports, 40 GPIO pins, Full HDMI port, Combined 3.5mm audio jack and composite video
Camera interface (CSI),Display interface (DSI), Micro SD card slot (now push-pull rather than push-push), VideoCore IV 3D graphics core

-----------------------------
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by andrew-buckley** [comment]
Hi @bironology, can you please paste the output from the command window too? Thanks!

**Comment by bironology** [comment]
Sure. Here it is. The line
`-- Installing azure_c_shared_utility. Please wait...
`
was displayed for a very long time (well over 10 minutes) before the error messages.
Thanks!


--
```
pi@raspberrypi:~/azure-iot-gateway-sdk $ ./tools/build.sh -c
~/azure-iot-gateway-sdk/build ~/azure-iot-gateway-sdk
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Install Prefix is /usr/local
-- AIG architecture: ARM
-- azure_c_shared_utility not found...
-- Building azure_c_shared_utility...
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared_Util architecture: ARM
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Checking for one of the modules 'uuid'
-- iothub architecture: ARM
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/azure-iot-gateway-sdk/deps/c-utility/build
-- Installing azure_c_shared_utility. Please wait...
CMake Error at gatewayFunctions.cmake:117 (message):
  Error installing azure_c_shared_utility: 2
Call Stack (most recent call first):
  dependencies.cmake:13 (findAndInstall)
  CMakeLists.txt:163 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pi/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/azure-iot-gateway-sdk/build/CMakeFiles/CMakeError.log".

```

**Comment by andrew-buckley** [comment]
Gotcha, can you also paste the output of these two files:
**/deps/c-utility/build/output.txt** and **/deps/c-utility/build/errors.txt**

**Comment by damonbarry** [comment]
Not a lot of activity, so closing.
