### ISSUE TITLE
Build Failure on tools\build.cmd --enable-dotnet-binding

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-gateway-sdk#81]
Hi,

I get the following error when trying to run tools\build.cmd --enable-dotnet-binding
Running it on Windows 10 x64.

Thanks!

Determining if the _M_AMD64 exist failed with the following output:
Change Dir: C:/Projects/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_53b70.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 23.12.2016 20:33:22.
Project "C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_53b70.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "cmTC_53b70.dir\Debug\".
  Creating directory "C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\Debug\".
  Creating directory "cmTC_53b70.dir\Debug\cmTC_53b70.tlog\".
InitializeBuildStatus:
  Creating "cmTC_53b70.dir\Debug\cmTC_53b70.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_53b70.dir\Debug\\" /Fd"cmTC_53b70.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"
  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_53b70.dir\Debug\\" /Fd"cmTC_53b70.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"
  
  CheckSymbolExists.c
C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_53b70.vcxproj]
Done Building Project "C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_53b70.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_53b70.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\Projects\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_53b70.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.43

File C:/Projects/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_AMD64
  return ((int*)(&_M_AMD64))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by smetsth** [comment]
Hi @vslepakov ,

I have the same issue. Have you been able to resolve this?
It looks like I'm on the same Visual Studio, MSBuild and C/C++ Compiler versions.

My Visual Studio setup didn't include C/C++ support until yesterday. I added those components afterwards. Maybe that's why I'm running into issues now?

Thanks
Thomas

**Comment by darobs** [comment]
Hello @vslepakov and @smetsth, there are a couple of things to try to get it working:
- If you have the master branch checked out, try checking out the develop branch
- Sometimes, I get this error when attempting to build one platform, and then switch to a new platform (like switching between 32 and 64 bit windows) without cleaning out the libraries from the previous build. If you have a "C:\Projects\azure-iot-gateway-sdk\install-deps" directory, try deleting that.

Please let me know if that fixes the problem.

Thanks,
Dave

**Comment by vslepakov** [comment]
Hi @darobs , hi @smetsth thanks for your input. Unfortunately both suggested steps did not resolve the issue. Here is the console output when building on develop (the problem seems to be with deps/umock-c:

Regards
Vitaliy

C:\Projects\temp\azure-iot-gateway-sdk\tools>build.cmd --enable-dotnet-binding
Cleaning up build artifacts...
The system cannot find the file specified.
***Running CMAKE for Win32***
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Install Prefix is C:/Program Files (x86)/azure_iot_gateway_sdk-1.0.0/
-- AIG architecture: x86
-- ctest not found...
-- Building ctest...
Submodule 'deps/ctest' (https://github.com/azure/azure-ctest) registered for path 'deps/ctest'
Cloning into 'C:/Projects/temp/azure-iot-gateway-sdk/deps/ctest'...
Submodule path 'deps/ctest': checked out 'c06affbd946f071e42cfd14bcebe4255a67d8df3'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/temp/azure-iot-gateway-sdk/deps/ctest/build
-- Installing ctest. Please wait...
-- testrunnerswitcher not found...
-- Building testrunnerswitcher...
Submodule 'deps/testrunner' (https://github.com/azure/azure-c-testrunnerswitcher) registered for path 'deps/testrunner'
Cloning into 'C:/Projects/temp/azure-iot-gateway-sdk/deps/testrunner'...
Submodule path 'deps/testrunner': checked out '03e34ead9c3d1bc1ec2e0fad4671c1f21f5c659b'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/temp/azure-iot-gateway-sdk/deps/testrunner/build
-- Installing testrunnerswitcher. Please wait...
-- umock_c not found...
-- Building umock_c...
Submodule 'deps/umock-c' (https://github.com/azure/umock-c) registered for path 'deps/umock-c'
Cloning into 'C:/Projects/temp/azure-iot-gateway-sdk/deps/umock-c'...
Submodule path 'deps/umock-c': checked out 'feeec3d14a9f03014d15c7eadbad0201544f9a6f'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/temp/azure-iot-gateway-sdk/deps/umock-c/build
-- Installing umock_c. Please wait...
CMake Error at gatewayFunctions.cmake:117 (message):
  Error installing umock_c: 1
Call Stack (most recent call first):
  dependencies-test.cmake:19 (findAndInstall)
  CMakeLists.txt:163 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Projects/temp/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
See also "C:/Projects/temp/azure-iot-gateway-sdk/build/CMakeFiles/CMakeError.log".

**Comment by darobs** [comment]
I will continue to look for solutions today.  Thanks for your patience, @vslepakov.

**Comment by vslepakov** [comment]
Thanks @darobs. You are right about me not using the dev command prompt. I will give it a try with dev command prompt on January, 2nd. I'll post the results  here.

Best Regards
Vitaliy

**Comment by damonbarry** [comment]
@vslepakov did you get the chance to try this with the Developer Command Prompt?

**Comment by vslepakov** [comment]
@darobs , @damonbarry thank you guys so much. using dev command prompt did the trick
