### ISSUE TITLE
Unable to run node module in windows service

### ISSUE THREAD

**Issue by AdamMachera** [Azure/azure-iot-gateway-sdk#83]
I'm unable to make up and running node js module from windows service.
I have created simple windows service that uses field gateway sdk.
To be able to construct field gateway inside windows service I extended sdk in branch 
https://github.com/AdamMachera/azure-iot-gateway-sdk.git
And added to dotnet.dll two methods
Module_DotNetHost_Gateway_CreateFromJson
Module_DotNetHost_Gateway_Destroy
Which I'm using from managed code.

Compiled librabries from this repositories are checked in into repository
https://github.com/AdamMachera/FieldGatewayNodeHost.git
This repository contains project of windows service that can be run from console application and can be installed as windows service.

Download latest version of above repository and build it locally.
A. Running from cmd
1. Open command prompt
2. go into bin\Debug folder and run
3. FieldGatewayHost.exe /DebugInConsole

you should see something like this:
"SampleService 2016-12-29 15:24:56.5939 DEBUG Starts FieldGatewayService
SampleService 2016-12-29 15:24:56.6334 DEBUG FG created successfully
c:\\
publishing message from sensor
publishing message from sensor
"
press any key and you see something like this
"SampleService 2016-12-29 15:24:59.3760 DEBUG Stops FieldGatewayHost
sensor.destroy
SampleService 2016-12-29 15:24:59.6400 DEBUG FieldGatewayHost was stopped"

B. Running this as service: 
1. Open command prompt as administrator
2. sc create FieldGatewayHost binPath= "c:\s\FieldGatewayNodeHost\FieldGatewayHost\bin\Debug\FieldGatewayHost.exe"
(notice that after binPath= there should be space and c:\s\FieldGatewayNodeHost\FieldGatewayHost\bin\Debug\ should be replaced with path where your repository is).
3. open services.msc window
4. try to start service FieldGatewayHost
5. It should fail
6. Open file 
c:\s\FieldGatewayNodeHost\FieldGatewayHost\bin\Debug\node\sensor.js and comment out all occurrences of console.log
7. Start service FieldGatewayHost
8. It should be running

Logs of starting and stopping are available inside logs folder (inside bin\Debug).

Module is failing probably because of console.log usage.

**Comment by avranju** [comment]
I am not entirely sure what we can do in this case. I would imagine that when running a gateway as a Windows service with Node.js modules, you may want to replace calls to `console.log` with something that logs to the Windows Event Log instead. The [node-windows](https://github.com/coreybutler/node-windows) is a package that appears to have some APIs that you can use for this. There are other options out there as well - logging to a file for instance.

The sample code in `sensor.js` is just that - a sample. You should feel free to modify it as appropriate to your use case.
