### ISSUE TITLE
Add better error handling for non-Ascii/UTF-8 encoded JSON config files

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-gateway-sdk#85]
Currently the `parson` lib seems to only supports `utf-8` and `ascii` encoded files for calls to `json_parse_file`, and the gateway just errors out with a generic "can't open file" message.  Given that many text editors and shells (e.g. PowerShell) will default to creating/saving files as "Unicode" (e.g. PowerShell's Out-File function, *which should be codepage 1252?*), it would be helpful to have the Gateway error out with a more useful message on file open issues that suggest encoding problems as a starting point for troubleshooting.  There should also likely be documentation that notes potential file encoding problems.

**Comment by WilliamBerryiii** [comment]
Agreed that documenting is probably preferable in this case.  

If I'm not mistaken the default text editors Notepad (windows), Wordpad (old windows) and TextEdit (mac) save to ANSI which may or may not have the issue with including/excluding the BOM and/or defaulting to the 1252 codepage(for windows).  

And I did indeed solve my file encoding issue with the `-Encoding` arg for out-file.

**Comment by damonbarry** [comment]
I made changes to several markdown files, commit ID is 1fc89fc.

**Comment by WilliamBerryiii** [comment]
Thanks @damonbarry!
