### ISSUE TITLE
Build fails - error C2065: '_M_AMD64': undeclared identifier

### ISSUE THREAD

**Issue by terrymandin** [Azure/azure-iot-gateway-sdk#87]
I am receiving an error when I build.  See details below:

==============
Command line output
==============

C:\tmp\iotgwsdk\azure-iot-gateway-sdk\tools>build
Cleaning up build artifacts...
The system cannot find the file specified.
***Running CMAKE for Win32***
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Install Prefix is C:/Program Files (x86)/azure_iot_gateway_sdk-1.0.0/
-- AIG architecture: x86
-- ctest not found...
-- Building ctest...
Submodule 'deps/ctest' (https://github.com/azure/azure-ctest) registered for path 'deps/ctest'
Cloning into 'C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/ctest'...
Submodule path 'deps/ctest': checked out 'c06affbd946f071e42cfd14bcebe4255a67d8df3'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/ctest/build
-- Installing ctest. Please wait...
-- testrunnerswitcher not found...
-- Building testrunnerswitcher...
Submodule 'deps/testrunner' (https://github.com/azure/azure-c-testrunnerswitcher) registered for path 'deps/testrunner'
Cloning into 'C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/testrunner'...
Submodule path 'deps/testrunner': checked out '03e34ead9c3d1bc1ec2e0fad4671c1f21f5c659b'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/testrunner/build
-- Installing testrunnerswitcher. Please wait...
-- umock_c not found...
-- Building umock_c...
Submodule 'deps/umock-c' (https://github.com/azure/umock-c) registered for path 'deps/umock-c'
Cloning into 'C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/umock-c'...
Submodule path 'deps/umock-c': checked out 'feeec3d14a9f03014d15c7eadbad0201544f9a6f'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/umock-c/build
-- Installing umock_c. Please wait...
-- azure_c_shared_utility not found...
-- Building azure_c_shared_utility...
Submodule 'deps/azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility) registered for path 'deps/c-utility'
Cloning into 'C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/c-utility'...
Submodule path 'deps/c-utility': checked out 'e8f4077bdb7c8fbdfe2df7c9e90297e22a9c6708'
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared_Util architecture: x86
CMake Error at testtools/micromock/CMakeLists.txt:60 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.

-- iothub architecture: x86
-- Configuring incomplete, errors occurred!
See also "C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/c-utility/build/CMakeFiles/CMakeOutput.log".
See also "C:/tmp/iotgwsdk/azure-iot-gateway-sdk/deps/c-utility/build/CMakeFiles/CMakeError.log".
CMake Error at gatewayFunctions.cmake:104 (message):
  Error running cmake for azure_c_shared_utility: 1
Call Stack (most recent call first):
  dependencies.cmake:13 (findAndInstall)
  CMakeLists.txt:163 (include)

-- Configuring incomplete, errors occurred!
See also "C:/tmp/iotgwsdk/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
See also "C:/tmp/iotgwsdk/azure-iot-gateway-sdk/build/CMakeFiles/CMakeError.log".

=============
CMakeError Output
=============

Determining if the _M_AMD64 exist failed with the following output:
Change Dir: C:/tmp/iotgwsdk/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_99ed9.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/5/2017 7:25:27 AM.

Project "C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_99ed9.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_99ed9.dir\Debug\".

  Creating directory "C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_99ed9.dir\Debug\cmTC_99ed9.tlog\".

InitializeBuildStatus:

  Creating "cmTC_99ed9.dir\Debug\cmTC_99ed9.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_99ed9.dir\Debug\\" /Fd"cmTC_99ed9.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_99ed9.dir\Debug\\" /Fd"cmTC_99ed9.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c"

  

  CheckSymbolExists.c

C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_99ed9.vcxproj]

Done Building Project "C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_99ed9.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_99ed9.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(7): error C2065: '_M_AMD64': undeclared identifier [C:\tmp\iotgwsdk\azure-iot-gateway-sdk\build\CMakeFiles\CMakeTmp\cmTC_99ed9.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.40

File C:/tmp/iotgwsdk/azure-iot-gateway-sdk/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _M_AMD64
  return ((int*)(&_M_AMD64))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by terrymandin** [comment]
Building development branch also fails (details below).  

-- Installing umock_c. Please wait...
CMake Error at gatewayFunctions.cmake:117 (message):
  Error installing umock_c: 1
Call Stack (most recent call first):
  dependencies-test.cmake:19 (findAndInstall)
  CMakeLists.txt:163 (include)


-- Configuring incomplete, errors occurred!
See also "C:/tmp/iotgwdev/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
See also "C:/tmp/iotgwdev/azure-iot-gateway-sdk/build/CMakeFiles/CMakeError.log".

**Comment by vslepakov** [comment]
Try Building using the Developer Command Prompt. It did the trick for me

**Comment by terrymandin** [comment]
Thanks!  That got me a bit further:

Build succeeded.
    0 Warning(s)
    0 Error(s)

According to this [page](https://github.com/Azure/iot-gateway-opc-ua) the following files should have been created, but they are not there:

- Microsoft.Azure.IoT.Gateway.dll
- Microsoft.Azure.IoT.Gateway.pdb
- dotnet.dll
- dotnet.pdb

I ran "build.cmd".  Was there another step that is required?

**Comment by darobs** [comment]
Hi @terrymandin, the dotnet bindings aren't built by default.
Please run the following:
tools\build_dotnet.cmd
tools\build.cmd --enable-dotnet-binding
(in a Developer Prompt :) )

That should get you what you want.
Thanks,
Dave

**Comment by terrymandin** [comment]
Thank you, I now have the dll's I require.  Much appreciated!
