### ISSUE TITLE
How to receive event from cloud ?

### ISSUE THREAD

**Issue by chaolong0129** [Azure/azure-iot-gateway-sdk#9]
Hi,
   Recently, I study the azure-iot-gateway-sdk. I can build it successfully. I also test it and add debug message. it always push the data to my iot-hub successfully. I found when I use device-explorer utility, my simulated_device_cloud_upload_sample can not receive the message from cloud. It just begins to receive at first time, then it would not receive any message. If I want to receive the message from device-explorer, how should I  do? Would you give me a point or suggestion ? 
Thanks,

**Comment by darobs** [comment]
@chaolong0129, the default polling time for receiving message in the HTTP transport is set fairly high (minutes), so you will not see an immediate response. If you would like to see faster responses, you may add a call like this
```c
unsigned int pollingTime = 10; //seconds between polling times
IoTHubClient_SetOption(result->iothubHandle, "MinimumPollingTime", &pollingTime);
```
into `PERSONALITY_create` after the IoTHubClient handle has been created.

Note that depending on volume of messages, this may be subject to throttling, for more details, see [IoT Hub throttling and you](https://azure.microsoft.com/en-us/blog/iot-hub-throttling-and-you/).
