### ISSUE TITLE
Cannot build from released source code.

### ISSUE THREAD

**Issue by ahidaka** [Azure/azure-iot-gateway-sdk#91]
Error message:
$ ./tools/build.sh --skip-unittests
fatal: Not a git repository (or any of the parent directories): .git

Source code:
https://github.com/Azure/azure-iot-gateway-sdk/archive/2016-12-16.tar.gz
from
https://github.com/Azure/azure-iot-gateway-sdk/releases

**Comment by darobs** [comment]
Hello @ahidaka, we're using git submodules as part of our build, and the .zip file does not contain any git information. 

We recommend you clone the repository, rather than download the zip file.

**Comment by ahidaka** [comment]
OK, thanks. I understand 2016-12-16.tar.gz is just for the documentation, not for build.
I recommend to add such kind of comment to https://github.com/Azure/azure-iot- gateway-sdk/releases.
"These Source codes (tar.gz) is not for build."

**Comment by darobs** [comment]
Good idea.  I added that note to our release tasks, thanks.

I'm going to close this issue, if you have any more concerns, please reopen this or open a new issue.
