### ISSUE TITLE
Windows 10 x64 build.cmd error

### ISSUE THREAD

**Issue by LeonardBae** [Azure/azure-iot-gateway-sdk#93]
I try to below command, but error occurred.
build.cmd --platform x64

error message is as a below.

C:\azure-iot-gateway-sdk\tools>build.cmd --platform x64
Cleaning up build artifacts...
***Running CMAKE for Win64***
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Install Prefix is C:/Program Files/azure_iot_gateway_sdk-1.0.0/
-- AIG architecture: x86_64
-- nanomsg not found...
-- Building nanomsg...
-- Detected nanomsg ABI v5.0.0
CMake Warning at CMakeLists.txt:252 (message):
  Could not find asciidoctor: skipping docs

-- Configuring done
-- Generating done
-- Build files have been written to: C:/azure-iot-gateway-sdk/deps/nanomsg/build
-- Installing nanomsg. Please wait...
CMake Error at install-deps/cmake/azure_c_shared_utilityFunctions.cmake:205 (if):
  if given arguments:

    "(" "(" "broker_ut" "MATCHES" ".*e2e.*" ")" "AND" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  core/tests/broker_ut/CMakeLists.txt:25 (build_test_artifacts)

-- Configuring incomplete, errors occurred!
See also "C:/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/698048/CMakeOutput.txt)

**Comment by LeonardBae** [comment]
and I tried too below command.
but error was occurred, too.

build.cmd --platform x64 --skip-unittests --enable-dotnet-binding

C:\azure-iot-gateway-sdk\tools>build.cmd --platform x64 --skip-unittests --enable-dotnet-binding
Cleaning up build artifacts...
***Running CMAKE for Win64***
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Install Prefix is C:/Program Files/azure_iot_gateway_sdk-1.0.0/
-- AIG architecture: x86_64
-- nanomsg not found...
-- Building nanomsg...
-- Detected nanomsg ABI v5.0.0
CMake Warning at CMakeLists.txt:252 (message):
  Could not find asciidoctor: skipping docs


-- Configuring done
-- Generating done
-- Build files have been written to: C:/azure-iot-gateway-sdk/deps/nanomsg/build
-- Installing nanomsg. Please wait...
-- uamqp not found...
-- Building uamqp...
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AMQP Target architecture: x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: C:/azure-iot-gateway-sdk/deps/uamqp/build
-- Installing uamqp. Please wait...
CMake Error at gatewayFunctions.cmake:117 (message):
  Error installing uamqp: 1
Call Stack (most recent call first):
  modules/dependencies.cmake:9 (findAndInstall)
  modules/CMakeLists.txt:6 (include)


-- Configuring incomplete, errors occurred!
See also "C:/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput2.txt](https://github.com/Azure/azure-iot-gateway-sdk/files/698069/CMakeOutput2.txt)

I want to test the sample "simulated_device_cloud_upload"

**Comment by darobs** [comment]
Hello @LeonardBae, I suspect the problem is in the `install-deps` folder.  If you delete this folder and run the build again, it will probably work. 

Usually, I get this cryptic error because I switched between 32 and 64 bit windows, and the `install-deps` folder only holds one set of binaries at a time.

**Comment by LeonardBae** [comment]
Downloading the sub-module solved the problem.
Thank you for your comments. @darobs
