### ISSUE TITLE
Error Loading Library running Java binding sample on Windows 10 x64

### ISSUE THREAD

**Issue by startemplar** [Azure/azure-iot-gateway-sdk#94]
Hi,
I get the following error when following the guide and trying to run tools\build.cmd --enable-java-binding
Running it on Windows 10 x64.
https://github.com/Azure/azure-iot-gateway-sdk/tree/develop/samples/java_sample

      "C:\src\azure\iot\azure-iot-gateway-sdk\build\azure_iot_gateway_sdk.sln" (default target) (1) ->
       "C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vcxproj.metaproj" (default target)
       (20) ->
       "C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vcxproj" (default target) (42) ->
       (Link target) ->
         java_module_host.obj : error LNK2019: unresolved external symbol __imp__JNI_GetDefaultJavaVMInitArgs@4 referen
       ced in function _init_vm_options [C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vc
       xproj]
         java_module_host.obj : error LNK2019: unresolved external symbol __imp__JNI_CreateJavaVM@12 referenced in func
       tion _JVM_Create [C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vcxproj]
         java_module_host.obj : error LNK2019: unresolved external symbol __imp__JNI_GetCreatedJavaVMs@12 referenced in
        function _JVM_Create [C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vcxproj]
         C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\Debug\java_module_host.dll : fatal error LNK1120: 3
        unresolved externals [C:\src\azure\iot\azure-iot-gateway-sdk\build\bindings\java\java_module_host.vcxproj]

    170 Warning(s)
    4 Error(s)

And there is no "Debug" folder under C:\src\azure\iot\azure-iot-gateway-sdk\build\samples\java_sample. I tried both on master/develop branch.

Thanks!

**Comment by startemplar** [comment]
Fixed by installing JDK x86 version and updating JAVA_HOME. But encountered another error
C:\src\azure\iot\azure-iot-gateway-sdk\build\samples\java_sample>Debug\java_sample.exe ..\..\..\samples\java_sample\src\java_sample_win.json
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\adapters\dynamic_library_windows.c Func:_DynamicLibrary_LoadLibrary Line:17 Error Loading Library. Error code is:  126
Info: Path is C:\Program Files (x86)\azure_iot_gateway_sdk-1.0.0\lib\modules\java_module_host.dll
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\adapters\dynamic_library_windows.c Func:_DynamicLibrary_LoadLibrary Line:17 Error Loading Library. Error code is:  126
Info: Path is C:\Program Files (x86)\azure_iot_gateway_sdk-1.0.0\lib\modules\java_module_host.dll
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\adapters\dynamic_library_windows.c Func:_DynamicLibrary_LoadLibrary Line:17 Error Loading Library. Error code is:  126
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\src\module_loaders\java_loader.c Func:_JavaModuleLoader_LoadBindingModule Line:70 The Java binding module could not be located.
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\src\module_loaders\java_loader.c Func:_JavaModuleLoader_Load Line:114 JavaModuleLoader_LoadBindingModule returned NULL
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\src\gateway_internal.c Func:_gateway_addmodule_internal Line:399 Failed to add module because the module could not be loaded.
Error: Time:Tue Jan 10 21:35:00 2017 File:C:\src\azure\iot\azure-iot-gateway-sdk\core\src\gateway_createfromjson.c Func:_Gateway_CreateFromJson Line:75 Failed to create gateway using lower level library.
failed to create the gateway from JSON

**Comment by BXCellent** [comment]
I had the same problem, so I fixed it manually by doing:
mkdir "C:\Program Files (x86)\azure_iot_gateway_sdk-1.0.0\lib\modules"
copy {installdir}\build\bindings\java\Debug\java_module_host.dll "C:\Program Files (x86)\azure_iot_gateway_sdk-1.0.0\lib\modules"

It then didn't find jvm.dll so I had to add the jdk1.8.0_112_x386\jre\bin and jdk1.8.0_112_x386\jre\bin\server to the PATH environment variable.

**Comment by andrew-buckley** [comment]
Hi @startemplar and @BXCellent, there is an option you can add to the JSON Configuration file under the Java Loader configuration. The gateway will search in you system install directory to try to find the native binding module. If you don't have the gateway installed on your machine, you can add the key `"binding.path"` to the java loader configuration with the path to the `java_module_host.dll`:

```
...
"loaders": [
      {
          "type": "java",
          "name": "java",
          "configuration":{
              "jvm.options":{
                  "library.path": "..\\..\\bindings\\java\\Debug"
              },
              "binding.path": "..\\..\\bindings\\java\\Debug\\java_module_host.dll"
          }
          
      }
  ],
...
```

**Comment by andrew-buckley** [comment]
Additionally, don't forget to setup your environment as described [here](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/java_sample/java_devbox_setup.md).

**Comment by JagatjyotiMohanty007** [comment]
Step1:- After successful building the program when I am running this its throwing me the below exception.
Could please help me in resolving the same.

![capture](https://cloud.githubusercontent.com/assets/25581230/23850698/708536d8-07d8-11e7-96b3-99d433127253.PNG)

**Comment by JagatjyotiMohanty007** [comment]
![image](https://cloud.githubusercontent.com/assets/25581230/23850800/de651344-07d8-11e7-8593-788530a17c06.png)
