### ISSUE TITLE
Can't install SDK on linux with node.js binding

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/azure-iot-gateway-sdk#95]
Greetings again. I have tried to install this on 3 different Linux versions. I'm out of ideas of fixing this so I hope you can help me.

Redhat 7 => After "./build.sh --enable-nodejs-binding" it can't find 'uuid'. The fix should be "yum install uuid-dev". Unfortunately this can't be installed. I also tried to load the right .tar.gz and .rpm and make uuid-dev but that didn't work as well (probably a problem with Redhat 7).

Redhat 6 => Breaks up after "./build_nodejs.sh". Probably the gcc is not high enough (4.4.7). I tried to install version 4.8 but no luck...

And finaly Xubuntu: 4.2.0-42-generic =>  After "./build.sh --enable-nodejs-binding" I get this:

> ./build.sh --enable-nodejs-binding
> ~/azure/build ~/azure
> -- The C compiler identification is GNU 5.2.1
> -- The CXX compiler identification is GNU 5.2.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMake Install Prefix is /usr/local
> -- AIG architecture: x86_64
> -- azure_c_shared_utility not found...
> -- Building azure_c_shared_utility...
> -- The C compiler identification is GNU 5.2.1
> -- The CXX compiler identification is GNU 5.2.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Shared_Util architecture: x86_64
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
> -- checking for one of the modules 'uuid'
> -- iothub architecture: x86_64
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/<name>/azure/deps/c-utility/build
> -- Installing azure_c_shared_utility. Please wait...
> CMake Error at gatewayFunctions.cmake:117 (message):
>   Error installing azure_c_shared_utility: 2
> Call Stack (most recent call first):
>   dependencies.cmake:13 (findAndInstall)
>   CMakeLists.txt:163 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/<name>/azure/build/CMakeFiles/CMakeOutput.log".

Did I do something wrong? Did I forget something?
Thanks for your help.

**Comment by andrew-buckley** [comment]
Hi @Zuendelmeister, please paste the output of these two files:
`~/azure/deps/c-utility/build/output.txt` and `~/azure/deps/c-utility/build/errors.txt`

**Comment by Zuendelmeister** [comment]
Hi @andrew-buckley , thank you so much for your fast response.
output.txt:

> Scanning dependencies of target micromock_ctest
> [  0%] [  1%] [  1%] Scanning dependencies of target aziotsharedutil
> Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/micromockcharstararenullterminatedstrings.cpp.o
> Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/micromockexception.cpp.o
> Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/micromocktestmutex.cpp.o
> [  1%] Building C object CMakeFiles/aziotsharedutil.dir/src/base64.c.o
> [  1%] Building C object CMakeFiles/aziotsharedutil.dir/src/buffer.c.o
> [  2%] Building C object CMakeFiles/aziotsharedutil.dir/src/constbuffer.c.o
> [  2%] Building C object CMakeFiles/aziotsharedutil.dir/src/consolelogger.c.o
> [  3%] Building C object CMakeFiles/aziotsharedutil.dir/src/crt_abstractions.c.o
> [  3%] Building C object CMakeFiles/aziotsharedutil.dir/src/constmap.c.o
> [  3%] Building C object CMakeFiles/aziotsharedutil.dir/src/doublylinkedlist.c.o
> [  4%] Building C object CMakeFiles/aziotsharedutil.dir/src/gballoc.c.o
> [  4%] Building C object CMakeFiles/aziotsharedutil.dir/src/gb_stdio.c.o
> [  5%] Building C object CMakeFiles/aziotsharedutil.dir/src/gb_time.c.o
> [  5%] Building C object CMakeFiles/aziotsharedutil.dir/src/hmac.c.o
> [  5%] [  5%] Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/mockcallrecorder.cpp.o
> Building C object CMakeFiles/aziotsharedutil.dir/src/hmacsha256.c.o
> [  6%] Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/mockmethodcallbase.cpp.o
> [  7%] Building C object CMakeFiles/aziotsharedutil.dir/src/xio.c.o
> [  7%] Building C object CMakeFiles/aziotsharedutil.dir/src/singlylinkedlist.c.o
> [  8%] [  8%] Building C object CMakeFiles/aziotsharedutil.dir/src/map.c.o
> Building C object CMakeFiles/aziotsharedutil.dir/src/sastoken.c.o
> [  8%] Building C object CMakeFiles/aziotsharedutil.dir/src/sha1.c.o
> [  9%] Building C object CMakeFiles/aziotsharedutil.dir/src/sha224.c.o
> [  9%] Building C object CMakeFiles/aziotsharedutil.dir/src/sha384-512.c.o
> [ 10%] Building C object CMakeFiles/aziotsharedutil.dir/src/strings.c.o
> [ 10%] Building C object CMakeFiles/aziotsharedutil.dir/src/string_tokenizer.c.o
> [ 10%] Building C object CMakeFiles/aziotsharedutil.dir/src/urlencode.c.o
> [ 11%] Building C object CMakeFiles/aziotsharedutil.dir/src/usha.c.o
> [ 11%] [ 12%] Building C object CMakeFiles/aziotsharedutil.dir/src/vector.c.o
> Building C object CMakeFiles/aziotsharedutil.dir/src/xlogging.c.o
> [ 12%] Building C object CMakeFiles/aziotsharedutil.dir/src/optionhandler.c.o
> [ 13%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/agenttime.c.o
> [ 13%] [ 13%] Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/mockvaluebase.cpp.o
> Building C object CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o
> [ 13%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/lock_pthreads.c.o
> [ 14%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/platform_linux.c.o
> [ 14%] [ 15%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/socketio_berkeley.c.o
> Building C object CMakeFiles/aziotsharedutil.dir/adapters/tickcounter_linux.c.o
> [ 16%] Building CXX object testtools/micromock/CMakeFiles/micromock_ctest.dir/src/timediscretemicromock.cpp.o
> [ 16%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/threadapi_pthreads.c.o
> [ 16%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_linux.c.o
> [ 17%] Building C object CMakeFiles/aziotsharedutil.dir/src/httpapiex.c.o
> [ 17%] Building C object CMakeFiles/aziotsharedutil.dir/src/httpapiexsas.c.o
> [ 17%] [ 18%] Building C object CMakeFiles/aziotsharedutil.dir/adapters/httpapi_curl.c.o
> Building C object CMakeFiles/aziotsharedutil.dir/src/httpheaders.c.o
> CMakeFiles/aziotsharedutil.dir/build.make:905: recipe for target 'CMakeFiles/aziotsharedutil.dir/adapters/httpapi_curl.c.o' failed
> CMakeFiles/Makefile2:928: recipe for target 'CMakeFiles/aziotsharedutil.dir/all' failed
> Linking CXX static library libmicromock_ctest.a
> [ 18%] Built target micromock_ctest
> Makefile:126: recipe for target 'all' failed


errors.txt:

> /home/<name>/azure/deps/c-utility/adapters/httpapi_curl.c:14:23: fatal error: curl/curl.h: No such file or directory
> compilation terminated.
> make[2]: *** [CMakeFiles/aziotsharedutil.dir/adapters/httpapi_curl.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/aziotsharedutil.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make: *** [all] Error 2

Seems that a file is missing. This is in the folder azure/deps/c-utility/adapters/:
agenttime.c             platform_freertos.c        threadapi_pthreads.c
agenttime_mbed.c        platform_linux.c           threadapi_rtx_mbed.cpp
condition_pthreads.c    platform_mbed.cpp          threadapi_win32.c
condition_rtx_mbed.cpp  platform_stub.c            tickcounter_freertos.c
condition_win32.c       platform_win32.c           tickcounter_linux.c
httpapi_compact.c       socketio_berkeley.c        tickcounter_mbed.cpp
httpapi_curl.c          socketio_mbed.c            tickcounter_tirtos.c
httpapi_tirtos.c        socketio_win32.c           tickcounter_win32.c
httpapi_wince.c         sslClient_arduino.cpp      tlsio_arduino.c
httpapi_winhttp.c       sslClient_arduino.h        tlsio_arduino.h
httpapi_wininet.c       tcpsocketconnection_c.cpp  uniqueid_linux.c
lock_pthreads.c         tcpsocketconnection_c.h    uniqueid_stub.c
lock_rtx_mbed.cpp       template                   uniqueid_win32.c
lock_win32.c            threadapi_arduino.c
platform_arduino.c      threadapi_freertos.c

Thanks again.

**Comment by andrew-buckley** [comment]
Seems like at least one dependency is missing from your machine, curl. [This document](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/doc/devbox_setup.md#set-up-a-linux-development-environment) provides a list of the dependencies you will need installed. Please install these and let me know what issues you run into. If you already have these installed please let me know!

**Comment by Zuendelmeister** [comment]
Aahh great hint. I installed all the dependencies. Unfortunately I have a new issue. It seems like the NODE_LIB and NODE_INCLUDE environment variables are wrong:

The program told me: Export the following variables so that the Azure IoT Gateway SDK build scripts can find these files.

> export NODE_INCLUDE="/home/<NAME>/azure/build_nodejs/dist/inc"
> export NODE_LIB="/home/<NAME>/azure/build_nodejs/dist/lib"

Which is what I did. Then i looked if it worked:

> ➜  tools git:(master) echo "$NODE_INCLUDE"
> /home/<NAME>/azure/build_nodejs/dist/inc
> 
> ➜  tools git:(master) echo "$NODE_LIB"
> /home/<NAME>/azure/build_nodejs/dist/lib

Here the output of ./build.sh --enable-nodejs-binding

> ~/azure/build ~/azure
> -- The C compiler identification is GNU 5.2.1
> -- The CXX compiler identification is GNU 5.2.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMake Install Prefix is /usr/local
> -- AIG architecture: x86_64
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
> -- NANOMSG LIBRARIES: nanomsg
> -- NANOMSG LDFLAGS: -L/home/<NAME>/azure/install-deps/lib;-lnanomsg
> -- NANOMSG CFLAGS: -I/home/<NAME/azure/install-deps/include
> -- checking for one of the modules 'uuid'
> -- checking for one of the modules 'gio-unix-2.0'
> CMake Error at bindings/nodejs/CMakeLists.txt:12 (message):
>   Environment variables NODE_INCLUDE and NODE_LIB are not defined.  Please
>   define NODE_INCLUDE to point to the location where the Node JS include
>   files reside and NODE_LIB to point to the location where the Node JS
>   library files reside.  If you haven't built Node JS yet, then please run
>   tools/build_nodejs.sh or tools/build_nodejs.cmd as appropriate.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/<NAME>/azure/build/CMakeFiles/CMakeOutput.log".

This is in /lib:
libcares.a        libicui18n.a      libnode.so     libv8_base.a           libv8_nosnapshot.a
libgtest.a        libicustubdata.a  libnode.so.48  libv8_inspector_stl.a  libv8_snapshot.a
libhttp_parser.a  libicutools.a     libopenssl.a   libv8_libbase.a        libzlib.a
libicudata.a      libicuucx.a       libuv.a        libv8_libplatform.a

And this is in /inc:
android-ifaddrs.h  node_version.h     uv-aix.h     uv-linux.h       uv-win.h           v8-platform.h
env.h              pthread-barrier.h  uv-bsd.h     uv-sunos.h       v8config.h         v8-profiler.h
env-inl.h          pthread-fixes.h    uv-darwin.h  uv-threadpool.h  v8-debug.h         v8-testing.h
libplatform        stdint-msvc2008.h  uv-errno.h   uv-unix.h        v8-experimental.h  v8-util.h
node.h             tree.h             uv.h         uv-version.h     v8.h               v8-version.h

I'm kinda confused. It should work right?
Thanks again.

**Comment by avranju** [comment]
The extra `/` in the paths for the variables `NODE_INCLUDE` and `NODE_LIB` seems redundant. Can you try removing that please? So instead of `/home//azure/build_nodejs/dist/inc` for example,  you might want to try `/home/azure/build_nodejs/dist/inc`. Also, are these paths real - i.e. do the include and lib folders contain the include, lib and SO files?

Finally, have you *exported* these variables from your shell, i.e., you'll need to do:

```
export NODE_INCLUDE=/home/azure/build_nodejs/dist/inc
```

instead of just

```
NODE_INCLUDE=/home/azure/build_nodejs/dist/inc
```

**Comment by Zuendelmeister** [comment]
Good catch. I didn't see the "//". Its strange that the install script told me to use those paths. I just copied and pasted. My fault. So now I fixed the paths but the same happens:

> ➜  tools git:(master) sudo ./build.sh --enable-nodejs-binding
> ~/azure/build ~/azure
> -- The C compiler identification is GNU 5.2.1
> -- The CXX compiler identification is GNU 5.2.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMake Install Prefix is /usr/local
> -- AIG architecture: x86_64
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
> -- NANOMSG LIBRARIES: nanomsg
> -- NANOMSG LDFLAGS: -L/home/<NAME>/azure/install-deps/lib;-lnanomsg
> -- NANOMSG CFLAGS: -I/home/<NAME>/azure/install-deps/include
> -- checking for one of the modules 'uuid'
> -- checking for one of the modules 'gio-unix-2.0'
> CMake Error at bindings/nodejs/CMakeLists.txt:12 (message):
>   Environment variables NODE_INCLUDE and NODE_LIB are not defined.  Please
>   define NODE_INCLUDE to point to the location where the Node JS include
>   files reside and NODE_LIB to point to the location where the Node JS
>   library files reside.  If you haven't built Node JS yet, then please run
>   tools/build_nodejs.sh or tools/build_nodejs.cmd as appropriate.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/<NAME>/azure/build/CMakeFiles/CMakeOutput.log".
> ➜  tools git:(master) echo "$NODE_LIB"
> /home/azure/build_nodejs/dist/lib
> ➜  tools git:(master) echo "$NODE_INCLUDE"
> /home//azure/build_nodejs/dist/inc
> ➜  tools git:(master) #

**Comment by Zuendelmeister** [comment]
Ok i started from scratch and it worked great. Thank you guys so much. The last problem was probably because I set up the environment too late. Can be closed.
