### ISSUE TITLE
BLE gateway

### ISSUE THREAD

**Issue by LeonardBae** [Azure/azure-iot-gateway-sdk#97]
I am a bit curious about using azure-iot-gateway-sdk at this time.
I would like to use azure-iot-gateway-sdk on Winodws 10(and IoT Core in the future) to test interworking with real equipment(TI BLE Sensor Tag).
The scenarios in the links below only support LINUX, which I want to test on Windows.
Is there any way?
Or will you be providing support for Windows in the future?

**Comment by WilliamBerryiii** [comment]
Here is a [BluetoothLE example for UPW](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothLEClient).  I would think you could build a small dll leveraging the UWP APIs and drop it into your gateway module chain.

**Comment by avranju** [comment]
As of now there isn't a plan to support Windows for the BLE module. One option may be to do what @WilliamBerryiii suggests. Another option might to be write a module using Node.js via the [node-sensortag](https://github.com/sandeepmistry/node-sensortag) package.

**Comment by mtheolog** [comment]
Similarly, I am trying to use the  Simulated_device-cloud-upload sample on windows 10 iot core. Knowing that it it is not UWP I wonder if there is a custom suggestion that I could follow.

**Comment by damonbarry** [comment]
@mtheolog Are you wondering about using BLE on Windows? Not sure what you mean by "custom suggestion"...

**Comment by mtheolog** [comment]
I am trying to use the simulated device cloud upload sample. Right now I can build the gateway sdk on windows 10. But I want to run it on windows 10 iot core and I wonder how can I do it.

**Comment by damonbarry** [comment]
@mtheolog Alright, let's use #86 to address that. Closing this issue...
